Code created by: Lorena Espinosa, Johana Rátiva, Eduards Chipatecua 

Class: Procesamiento del Lenguaje Natural

University: Universidad de los Andes

Date: August 23, 2026

In [6]:
import xml.etree.ElementTree as ET
import re
import unicodedata
import math
import sys
import spacy
import pandas as pd
import numpy as np
import nltk
import import_ipynb
import Metricas_Evaluacion as metricas

from IPython.display import display
from nltk.stem import PorterStemmer
from nltk.tokenize import word_tokenize
from pathlib import Path
from rank_bm25 import BM25Okapi
from gensim import corpora, models, similarities

stemmer = PorterStemmer()
for recurso in ["punkt", "punkt_tab"]:
    nltk.download(recurso, quiet=True)

# Motores de Busqueda

## Procesamiento DataSet

### Lectura de documentos

el contenido empezaba con el titulo del documento, lo cual puede resultar en busquedas dobles en elementos donde solo esta una vez, por eso convienve filtrarlo desde la lectura

In [7]:
def read_naf_document(path):
    """ 
    Esta función lee un documento en formato NAF (Natural Annotation Format) desde la ruta especificada
    y extrae información relevante del mismo a partir de su estructura XML.
    Devuelve un diccionario con el 
        ID del documento, 
        el título y 
        el contenido del texto.

    Se limpia el contenido eliminando el título del mismo si este existe,
    y se eliminan los caracteres de puntuación y espacios en blanco al inicio del contenido.
    """
    tree = ET.parse(path) # abre el archivo NAF y lo parsea en un árbol XML
    root = tree.getroot() # obtiene la raíz del árbol XML 

    header = root.find("nafHeader") # acceso a los hijos del elemento raíz
    file_desc = header.find("fileDesc")
    public = header.find("public")
    raw = root.find("raw")
    titulo = file_desc.get("title")
    contenido = raw.text

    if titulo is not None:
        contenido = contenido[len(titulo):].lstrip(". \n")
        return {
            "id": public.get("publicId"),
            "titulo": titulo,
            "contenido": contenido}
    else:
        return {
            "id": public.get("publicId"),
            "contenido": contenido}

docs_path = Path("docs-raw-texts")
naf_files = list(docs_path.glob("*.naf"))
documents = []

for file_path in naf_files:
    document = read_naf_document(file_path)
    documents.append(document)

In [8]:
documents[0]

{'id': 'd001',
 'titulo': 'William Beaumont and the Human Digestion',
 'contenido': 'William Beaumont: Physiology of digestion Image Source.  On November 21, 1785, US-American\xa0surgeon William Beaumont was born. He became best known as “Father of Gastric Physiology” following his research on human\xa0digestion. William Beaumont was born in Lebanon, Connecticut and became a physician. He served as a surgeon’s mate\xa0in the Army\xa0during the War of 1812. He opened a private practice\xa0in Plattsburgh, New York, but rejoined the Army\xa0as a surgeon in 1819. Beaumont was stationed at Fort Mackinac on Mackinac Island in Michigan in the early 1820s when it existed to protect the interests of the American Fur Company. The fort became the refuge\xa0for a wounded 19-year-old French-Canadian fur trader named\xa0Alexis St. Martin\xa0when a shotgun went off by accident in the American Fur Company store at close range June 6th, 1822.\xa0St. Martin’s wound was quite serious because his\xa0stomach was perforated and several ribs\xa0were broken. Nobody really expected that the young man\xa0would survive but he really did. The skin\xa0around\xa0St. Martin’s\xa0wound fused to the hole in his stomach, leaving a permanent opening – a gastric fistula. [1] Beaumont\xa0quickly noticed that there was much research potential. Back then, not too much was known about the digestive system. In order to gain more information,\xa0Beaumont performed numerous experiments on\xa0St. Martin over a period of eight years. The experiments\xa0must have been really uncomfortable for the man, who was inserted bits of different foods tied to strings through the hole in his stomach, pulling them out periodically to observe digestion.\xa0Beaumont also removed gastric juice, examining it to better understand its nature.\xa0Beaumont became the “Father of Gastric Physiology” and his findings were published in the book\xa0“Experiments and Observations on the Gastric Juice and the Physiology of Digestion” in 1833. The work\xa0is now considered as the basis of much of the early knowledge on digestion. William Beaumont discovered that hydrochloric acid is the main chemical responsible for breaking down food and he suggested that another important digestive\xa0chemical, which is now known as pepsin. He suggested that digestion is a chemical process, not merely a mechanical one caused by stomach muscle movement. Also,\xa0Beaumont gave insights on how emotions, temperature, and physical activity\xa0can affect digestion.\xa0Beaumont’s famous patient, St. Martin, outlived the scientist even though his wound never completely healed. He had several children and died at the age\xa0of 83. [2] At yovisto, you may be interested in a video lecture on The Digestive System.'}

### Pre-Procesamiento.Limpieza y normalizacion

In [9]:
def clean_text(text):
    """ 
    Esta función limpia el texto de un documento eliminando etiquetas HTML y URLs.
    Además, reemplaza múltiples espacios en blanco por un solo espacio y elimina los espacios al inicio 
    y al final del texto.
    """
    text = re.sub(r"<[^>]+>", " ", text)
    text = re.sub(r"https?://\S+|www\.\S+", " ", text)
    return re.sub(r"\s+", " ", text).strip()

def normalize_text(text, remove_accents=False):
    """ 
    Esta función normaliza el texto de un documento, 
    convirtiéndolo a minúsculas y eliminando acentos si es necesario.
    """
    text = unicodedata.normalize("NFKC", text).lower()
    if remove_accents:
        text = "".join(
            char
            for char in unicodedata.normalize("NFD", text)
            if unicodedata.category(char) != "Mn"
        )
    return text
for document in documents:
    texto = document["titulo"] + " " + document["contenido"]
    texto = clean_text(texto)
    document["contenido_limpio"] = normalize_text(texto, True)

In [10]:
documents[0]

{'id': 'd001',
 'titulo': 'William Beaumont and the Human Digestion',
 'contenido': 'William Beaumont: Physiology of digestion Image Source.  On November 21, 1785, US-American\xa0surgeon William Beaumont was born. He became best known as “Father of Gastric Physiology” following his research on human\xa0digestion. William Beaumont was born in Lebanon, Connecticut and became a physician. He served as a surgeon’s mate\xa0in the Army\xa0during the War of 1812. He opened a private practice\xa0in Plattsburgh, New York, but rejoined the Army\xa0as a surgeon in 1819. Beaumont was stationed at Fort Mackinac on Mackinac Island in Michigan in the early 1820s when it existed to protect the interests of the American Fur Company. The fort became the refuge\xa0for a wounded 19-year-old French-Canadian fur trader named\xa0Alexis St. Martin\xa0when a shotgun went off by accident in the American Fur Company store at close range June 6th, 1822.\xa0St. Martin’s wound was quite serious because his\xa0stomach was perforated and several ribs\xa0were broken. Nobody really expected that the young man\xa0would survive but he really did. The skin\xa0around\xa0St. Martin’s\xa0wound fused to the hole in his stomach, leaving a permanent opening – a gastric fistula. [1] Beaumont\xa0quickly noticed that there was much research potential. Back then, not too much was known about the digestive system. In order to gain more information,\xa0Beaumont performed numerous experiments on\xa0St. Martin over a period of eight years. The experiments\xa0must have been really uncomfortable for the man, who was inserted bits of different foods tied to strings through the hole in his stomach, pulling them out periodically to observe digestion.\xa0Beaumont also removed gastric juice, examining it to better understand its nature.\xa0Beaumont became the “Father of Gastric Physiology” and his findings were published in the book\xa0“Experiments and Observations on the Gastric Juice and the Physiology of Digestion” in 1833. The work\xa0is now considered as the basis of much of the early knowledge on digestion. William Beaumont discovered that hydrochloric acid is the main chemical responsible for breaking down food and he suggested that another important digestive\xa0chemical, which is now known as pepsin. He suggested that digestion is a chemical process, not merely a mechanical one caused by stomach muscle movement. Also,\xa0Beaumont gave insights on how emotions, temperature, and physical activity\xa0can affect digestion.\xa0Beaumont’s famous patient, St. Martin, outlived the scientist even though his wound never completely healed. He had several children and died at the age\xa0of 83. [2] At yovisto, you may be interested in a video lecture on The Digestive System.',
 'contenido_limpio': 'william beaumont and the human digestion william beaumont: physiology of digestion image source. on november 21, 1785, us-american surgeon william beaumont was born. he became best known as “father of gastric physiology” following his research on human digestion. william beaumont was born in lebanon, connecticut and became a physician. he served as a surgeon’s mate in the army during the war of 1812. he opened a private practice in plattsburgh, new york, but rejoined the army as a surgeon in 1819. beaumont was stationed at fort mackinac on mackinac island in michigan in the early 1820s when it existed to protect the interests of the american fur company. the fort became the refuge for a wounded 19-year-old french-canadian fur trader named alexis st. martin when a shotgun went off by accident in the american fur company store at close range june 6th, 1822. st. martin’s wound was quite serious because his stomach was perforated and several ribs were broken. nobody really expected that the young man would survive but he really did. the skin around st. martin’s wound fused to the hole in his stomach, leaving a permanent opening – a gastric fistula. [1] beaumont quickly noticed that there was much research potential. back then, not too much was known about the digestive system. in order to gain more information, beaumont performed numerous experiments on st. martin over a period of eight years. the experiments must have been really uncomfortable for the man, who was inserted bits of different foods tied to strings through the hole in his stomach, pulling them out periodically to observe digestion. beaumont also removed gastric juice, examining it to better understand its nature. beaumont became the “father of gastric physiology” and his findings were published in the book “experiments and observations on the gastric juice and the physiology of digestion” in 1833. the work is now considered as the basis of much of the early knowledge on digestion. william beaumont discovered that hydrochloric acid is the main chemical responsible for breaking down food and he suggested that another important digestive chemical, which is now known as pepsin. he suggested that digestion is a chemical process, not merely a mechanical one caused by stomach muscle movement. also, beaumont gave insights on how emotions, temperature, and physical activity can affect digestion. beaumont’s famous patient, st. martin, outlived the scientist even though his wound never completely healed. he had several children and died at the age of 83. [2] at yovisto, you may be interested in a video lecture on the digestive system.'}

### Tokenizacion
Se seleccionó spaCy como tokenizer porque su segmentación permite separar términos unidos por signos de puntuación, como guiones, y conservar sus componentes como tokens independientes. Esto resulta conveniente para la recuperación booleana mediante índice invertido, ya que permite que términos individuales como jean o nicolas puedan ser indexados y recuperados independientemente.en la tabla se puede ver las evidencias de eso

In [11]:
def tokenize_nltk(text):
    return word_tokenize(text)

nlp = spacy.load("en_core_web_sm")
def tokenize_spacy(text):
    doc = nlp(text)
    return [token.text for token in doc]

In [12]:
print(nlp.pipe_names)

['tok2vec', 'tagger', 'parser', 'attribute_ruler', 'lemmatizer', 'ner']

In [13]:
nlp("Ayuda a entender")

Ayuda a entender

In [14]:
def compare_tokens(tokens_nltk, tokens_spacy):
    """
    Esta función compara dos listas de tokens generadas por NLTK y spaCy, respectivamente.
    Devuelve dos listas:
    - Tokens que están presentes en la lista de NLTK pero no en la de spaCy.
    - Tokens que están presentes en la lista de spaCy pero no en la de NLTK.
    """
    set_nltk = set(tokens_nltk)
    set_spacy = set(tokens_spacy)

    solo_nltk = [token for token in tokens_nltk if token not in set_spacy]
    solo_spacy = [token for token in tokens_spacy if token not in set_nltk]

    return solo_nltk, solo_spacy

resultados = []

for document in documents:
    texto = document["contenido_limpio"]

    tokens_nltk = tokenize_nltk(texto)
    tokens_spacy = tokenize_spacy(texto)

    set_nltk = set(tokens_nltk)
    set_spacy = set(tokens_spacy)

    solo_nltk = [token for token in tokens_nltk if token not in set_spacy]
    solo_spacy = [token for token in tokens_spacy if token not in set_nltk]

    resultados.append({
        "id": document["id"],
        "titulo": document["titulo"],
        "tokens_nltk": len(tokens_nltk),
        "tokens_spacy": len(tokens_spacy),
        "diferencia": len(tokens_nltk) - len(tokens_spacy),
        "solo_NLTK": solo_nltk,
        "solo_spaCy": solo_spacy
    })

comparacion = pd.DataFrame(resultados)

display(comparacion)

,id,titulo,tokens_nltk,tokens_spacy,diferencia,solo_NLTK,solo_spaCy
0,d001,William Beaumont and the Human Digestion,484,497,-13,"[us-american, ’, s, 1812., 1819., 19-year-old,...","[us, -, ’s, 1812, 1819, 19, -, year, -, old, f..."
1,d002,Selma Lagerlöf and the wonderful Adventures of...,516,513,3,"[s, 1890., s, 1900., s, s]","[’s, 1890, book‘s, 1900, ’s, ’s]"
2,d003,Ferdinand de Lesseps and the Suez Canal,994,998,-4,"[1805-1894, ‘, s, career-diplomats, vice-consu...","[-, 1894, lessep‘s, -, diplomats, vice, -, con..."
3,d004,Walt Disney’s ‘Steamboat Willie’ and the Rise ...,559,560,-1,"[s, s, black-and-white, s, s, s, s, sound-on-f...","[’s, ’s, black, -, -, white, ’s, ’s, ’s, ’s, -..."
4,d005,Eugene Wigner and the Structure of the Atomic ...,694,696,-2,"[1902-1995, ’, s, ’, s, ’, s, x-ray, s, d-matr...","[1995, ’s, ’s, ’s, x, ray, hilbert‘s, d, matri..."
...,...,...,...,...,...,...,...
326,d327,James Parkinson and Parkinson’s Disease,557,553,4,"[’, s, s, 1886., s, s, under-privileged, post-...","[’s, parkinson‘s, 1886, parkinson‘s, parkinson..."
327,d328,Juan de la Cierva and the Autogiro,896,896,0,"[oct., 1925., single-rotor, today, ‘, s, [, 1,...","[oct, single, -, today‘s, it.[1, fixed, -, rot..."
328,d329,Squire Whipple – The Father of the Iron Bridge,482,484,-2,"[us-american, cotton-spinning, ’, s, short-lif...","[us, -, american, cotton, -, spinning, ’s, sho..."
329,d330,William Playfair and the Beginnings of Infogra...,927,920,7,"[’, s, trade-balance, time-series, mill-wright...","[’s, -, balance, -, mill, -, wright, playfair‘..."
330,d331,Juan Bautista de Anza and the Route to San Fra...,497,505,-8,"[1774., new-spanish, 1736., 1760., ’, s, 1774....","[1774, -, 1736, 1760, ’s, 1774, st, 1777]"

### Limpieza de tokens
Quitamos palabras de parada y puntuacion en los tockes

In [15]:
for document in documents:
    document["tokens"] = [ token for token in nlp(document["contenido_limpio"]) if not token.is_punct and not token.is_stop ]

In [16]:
documents[0]

{'id': 'd001',
 'titulo': 'William Beaumont and the Human Digestion',
 'contenido': 'William Beaumont: Physiology of digestion Image Source.  On November 21, 1785, US-American\xa0surgeon William Beaumont was born. He became best known as “Father of Gastric Physiology” following his research on human\xa0digestion. William Beaumont was born in Lebanon, Connecticut and became a physician. He served as a surgeon’s mate\xa0in the Army\xa0during the War of 1812. He opened a private practice\xa0in Plattsburgh, New York, but rejoined the Army\xa0as a surgeon in 1819. Beaumont was stationed at Fort Mackinac on Mackinac Island in Michigan in the early 1820s when it existed to protect the interests of the American Fur Company. The fort became the refuge\xa0for a wounded 19-year-old French-Canadian fur trader named\xa0Alexis St. Martin\xa0when a shotgun went off by accident in the American Fur Company store at close range June 6th, 1822.\xa0St. Martin’s wound was quite serious because his\xa0stomach was perforated and several ribs\xa0were broken. Nobody really expected that the young man\xa0would survive but he really did. The skin\xa0around\xa0St. Martin’s\xa0wound fused to the hole in his stomach, leaving a permanent opening – a gastric fistula. [1] Beaumont\xa0quickly noticed that there was much research potential. Back then, not too much was known about the digestive system. In order to gain more information,\xa0Beaumont performed numerous experiments on\xa0St. Martin over a period of eight years. The experiments\xa0must have been really uncomfortable for the man, who was inserted bits of different foods tied to strings through the hole in his stomach, pulling them out periodically to observe digestion.\xa0Beaumont also removed gastric juice, examining it to better understand its nature.\xa0Beaumont became the “Father of Gastric Physiology” and his findings were published in the book\xa0“Experiments and Observations on the Gastric Juice and the Physiology of Digestion” in 1833. The work\xa0is now considered as the basis of much of the early knowledge on digestion. William Beaumont discovered that hydrochloric acid is the main chemical responsible for breaking down food and he suggested that another important digestive\xa0chemical, which is now known as pepsin. He suggested that digestion is a chemical process, not merely a mechanical one caused by stomach muscle movement. Also,\xa0Beaumont gave insights on how emotions, temperature, and physical activity\xa0can affect digestion.\xa0Beaumont’s famous patient, St. Martin, outlived the scientist even though his wound never completely healed. He had several children and died at the age\xa0of 83. [2] At yovisto, you may be interested in a video lecture on The Digestive System.',
 'contenido_limpio': 'william beaumont and the human digestion william beaumont: physiology of digestion image source. on november 21, 1785, us-american surgeon william beaumont was born. he became best known as “father of gastric physiology” following his research on human digestion. william beaumont was born in lebanon, connecticut and became a physician. he served as a surgeon’s mate in the army during the war of 1812. he opened a private practice in plattsburgh, new york, but rejoined the army as a surgeon in 1819. beaumont was stationed at fort mackinac on mackinac island in michigan in the early 1820s when it existed to protect the interests of the american fur company. the fort became the refuge for a wounded 19-year-old french-canadian fur trader named alexis st. martin when a shotgun went off by accident in the american fur company store at close range june 6th, 1822. st. martin’s wound was quite serious because his stomach was perforated and several ribs were broken. nobody really expected that the young man would survive but he really did. the skin around st. martin’s wound fused to the hole in his stomach, leaving a permanent opening – a gastric fistula. [1] beaumont quickly noticed that there was much research potential. back then, not too much was known about the digestive system. in order to gain more information, beaumont performed numerous experiments on st. martin over a period of eight years. the experiments must have been really uncomfortable for the man, who was inserted bits of different foods tied to strings through the hole in his stomach, pulling them out periodically to observe digestion. beaumont also removed gastric juice, examining it to better understand its nature. beaumont became the “father of gastric physiology” and his findings were published in the book “experiments and observations on the gastric juice and the physiology of digestion” in 1833. the work is now considered as the basis of much of the early knowledge on digestion. william beaumont discovered that hydrochloric acid is the main chemical responsible for breaking down food and he suggested that another important digestive chemical, which is now known as pepsin. he suggested that digestion is a chemical process, not merely a mechanical one caused by stomach muscle movement. also, beaumont gave insights on how emotions, temperature, and physical activity can affect digestion. beaumont’s famous patient, st. martin, outlived the scientist even though his wound never completely healed. he had several children and died at the age of 83. [2] at yovisto, you may be interested in a video lecture on the digestive system.',
 'tokens': [william,
  beaumont,
  human,
  digestion,
  william,
  beaumont,
  physiology,
  digestion,
  image,
  source,
  november,
  21,
  1785,
  american,
  surgeon,
  william,
  beaumont,
  born,
  best,
  known,
  father,
  gastric,
  physiology,
  following,
  research,
  human,
  digestion,
  william,
  beaumont,
  born,
  lebanon,
  connecticut,
  physician,
  served,
  surgeon,
  mate,
  army,
  war,
  1812,
  opened,
  private,
  practice,
  plattsburgh,
  new,
  york,
  rejoined,
  army,
  surgeon,
  1819,
  beaumont,
  stationed,
  fort,
  mackinac,
  mackinac,
  island,
  michigan,
  early,
  1820s,
  existed,
  protect,
  interests,
  american,
  fur,
  company,
  fort,
  refuge,
  wounded,
  19,
  year,
  old,
  french,
  canadian,
  fur,
  trader,
  named,
  alexis,
  st,
  martin,
  shotgun,
  went,
  accident,
  american,
  fur,
  company,
  store,
  close,
  range,
  june,
  6th,
  1822,
  st,
  martin,
  wound,
  stomach,
  perforated,
  ribs,
  broken,
  expected,
  young,
  man,
  survive,
  skin,
  st,
  martin,
  wound,
  fused,
  hole,
  stomach,
  leaving,
  permanent,
  opening,
  gastric,
  fistula,
  1,
  beaumont,
  quickly,
  noticed,
  research,
  potential,
  known,
  digestive,
  system,
  order,
  gain,
  information,
  beaumont,
  performed,
  numerous,
  experiments,
  st,
  martin,
  period,
  years,
  experiments,
  uncomfortable,
  man,
  inserted,
  bits,
  different,
  foods,
  tied,
  strings,
  hole,
  stomach,
  pulling,
  periodically,
  observe,
  digestion,
  beaumont,
  removed,
  gastric,
  juice,
  examining,
  better,
  understand,
  nature,
  beaumont,
  father,
  gastric,
  physiology,
  findings,
  published,
  book,
  experiments,
  observations,
  gastric,
  juice,
  physiology,
  digestion,
  1833,
  work,
  considered,
  basis,
  early,
  knowledge,
  digestion,
  william,
  beaumont,
  discovered,
  hydrochloric,
  acid,
  main,
  chemical,
  responsible,
  breaking,
  food,
  suggested,
  important,
  digestive,
  chemical,
  known,
  pepsin,
  suggested,
  digestion,
  chemical,
  process,
  merely,
  mechanical,
  caused,
  stomach,
  muscle,
  movement,
  beaumont,
  gave,
  insights,
  emotions,
  temperature,
  physical,
  activity,
  affect,
  digestion,
  beaumont,
  famous,
  patient,
  st,
  martin,
  outlived,
  scientist,
  wound,
  completely,
  healed,
  children,
  died,
  age,
  83,
  2,
  yovisto,
  interested,
  video,
  lecture,
  digestive,
  system]}

### Steamming
Elegimos utilizar Porter Stemmer porque queremos que palabras que representan una misma idea, pero que aparecen en diferentes formas, puedan ser tratadas como un mismo término durante la búsqueda. Por ejemplo, engine y engines se convierten en engin, mientras que digestion y digestive se convierten en digest. Aunque el resultado no siempre sea una palabra real, esto no es un problema para nuestro motor, porque el stem se utiliza únicamente como término interno del índice. Así podemos aumentar las posibilidades de encontrar documentos relevantes aunque la consulta y el documento utilicen formas diferentes de una palabra.

Adicionalmente el proceso de stemming es menos costoso que el proceso de lematización dado que no requiere un recurso linguistico para generar el corte en la palabra.

In [17]:
for document in documents:
    document["tokens"] = [stemmer.stem(token.text) for token in document["tokens"]]

In [18]:
documents[0]

{'id': 'd001',
 'titulo': 'William Beaumont and the Human Digestion',
 'contenido': 'William Beaumont: Physiology of digestion Image Source.  On November 21, 1785, US-American\xa0surgeon William Beaumont was born. He became best known as “Father of Gastric Physiology” following his research on human\xa0digestion. William Beaumont was born in Lebanon, Connecticut and became a physician. He served as a surgeon’s mate\xa0in the Army\xa0during the War of 1812. He opened a private practice\xa0in Plattsburgh, New York, but rejoined the Army\xa0as a surgeon in 1819. Beaumont was stationed at Fort Mackinac on Mackinac Island in Michigan in the early 1820s when it existed to protect the interests of the American Fur Company. The fort became the refuge\xa0for a wounded 19-year-old French-Canadian fur trader named\xa0Alexis St. Martin\xa0when a shotgun went off by accident in the American Fur Company store at close range June 6th, 1822.\xa0St. Martin’s wound was quite serious because his\xa0stomach was perforated and several ribs\xa0were broken. Nobody really expected that the young man\xa0would survive but he really did. The skin\xa0around\xa0St. Martin’s\xa0wound fused to the hole in his stomach, leaving a permanent opening – a gastric fistula. [1] Beaumont\xa0quickly noticed that there was much research potential. Back then, not too much was known about the digestive system. In order to gain more information,\xa0Beaumont performed numerous experiments on\xa0St. Martin over a period of eight years. The experiments\xa0must have been really uncomfortable for the man, who was inserted bits of different foods tied to strings through the hole in his stomach, pulling them out periodically to observe digestion.\xa0Beaumont also removed gastric juice, examining it to better understand its nature.\xa0Beaumont became the “Father of Gastric Physiology” and his findings were published in the book\xa0“Experiments and Observations on the Gastric Juice and the Physiology of Digestion” in 1833. The work\xa0is now considered as the basis of much of the early knowledge on digestion. William Beaumont discovered that hydrochloric acid is the main chemical responsible for breaking down food and he suggested that another important digestive\xa0chemical, which is now known as pepsin. He suggested that digestion is a chemical process, not merely a mechanical one caused by stomach muscle movement. Also,\xa0Beaumont gave insights on how emotions, temperature, and physical activity\xa0can affect digestion.\xa0Beaumont’s famous patient, St. Martin, outlived the scientist even though his wound never completely healed. He had several children and died at the age\xa0of 83. [2] At yovisto, you may be interested in a video lecture on The Digestive System.',
 'contenido_limpio': 'william beaumont and the human digestion william beaumont: physiology of digestion image source. on november 21, 1785, us-american surgeon william beaumont was born. he became best known as “father of gastric physiology” following his research on human digestion. william beaumont was born in lebanon, connecticut and became a physician. he served as a surgeon’s mate in the army during the war of 1812. he opened a private practice in plattsburgh, new york, but rejoined the army as a surgeon in 1819. beaumont was stationed at fort mackinac on mackinac island in michigan in the early 1820s when it existed to protect the interests of the american fur company. the fort became the refuge for a wounded 19-year-old french-canadian fur trader named alexis st. martin when a shotgun went off by accident in the american fur company store at close range june 6th, 1822. st. martin’s wound was quite serious because his stomach was perforated and several ribs were broken. nobody really expected that the young man would survive but he really did. the skin around st. martin’s wound fused to the hole in his stomach, leaving a permanent opening – a gastric fistula. [1] beaumont quickly noticed that there was much research potential. back then, not too much was known about the digestive system. in order to gain more information, beaumont performed numerous experiments on st. martin over a period of eight years. the experiments must have been really uncomfortable for the man, who was inserted bits of different foods tied to strings through the hole in his stomach, pulling them out periodically to observe digestion. beaumont also removed gastric juice, examining it to better understand its nature. beaumont became the “father of gastric physiology” and his findings were published in the book “experiments and observations on the gastric juice and the physiology of digestion” in 1833. the work is now considered as the basis of much of the early knowledge on digestion. william beaumont discovered that hydrochloric acid is the main chemical responsible for breaking down food and he suggested that another important digestive chemical, which is now known as pepsin. he suggested that digestion is a chemical process, not merely a mechanical one caused by stomach muscle movement. also, beaumont gave insights on how emotions, temperature, and physical activity can affect digestion. beaumont’s famous patient, st. martin, outlived the scientist even though his wound never completely healed. he had several children and died at the age of 83. [2] at yovisto, you may be interested in a video lecture on the digestive system.',
 'tokens': ['william',
  'beaumont',
  'human',
  'digest',
  'william',
  'beaumont',
  'physiolog',
  'digest',
  'imag',
  'sourc',
  'novemb',
  '21',
  '1785',
  'american',
  'surgeon',
  'william',
  'beaumont',
  'born',
  'best',
  'known',
  'father',
  'gastric',
  'physiolog',
  'follow',
  'research',
  'human',
  'digest',
  'william',
  'beaumont',
  'born',
  'lebanon',
  'connecticut',
  'physician',
  'serv',
  'surgeon',
  'mate',
  'armi',
  'war',
  '1812',
  'open',
  'privat',
  'practic',
  'plattsburgh',
  'new',
  'york',
  'rejoin',
  'armi',
  'surgeon',
  '1819',
  'beaumont',
  'station',
  'fort',
  'mackinac',
  'mackinac',
  'island',
  'michigan',
  'earli',
  '1820',
  'exist',
  'protect',
  'interest',
  'american',
  'fur',
  'compani',
  'fort',
  'refug',
  'wound',
  '19',
  'year',
  'old',
  'french',
  'canadian',
  'fur',
  'trader',
  'name',
  'alexi',
  'st',
  'martin',
  'shotgun',
  'went',
  'accid',
  'american',
  'fur',
  'compani',
  'store',
  'close',
  'rang',
  'june',
  '6th',
  '1822',
  'st',
  'martin',
  'wound',
  'stomach',
  'perfor',
  'rib',
  'broken',
  'expect',
  'young',
  'man',
  'surviv',
  'skin',
  'st',
  'martin',
  'wound',
  'fuse',
  'hole',
  'stomach',
  'leav',
  'perman',
  'open',
  'gastric',
  'fistula',
  '1',
  'beaumont',
  'quickli',
  'notic',
  'research',
  'potenti',
  'known',
  'digest',
  'system',
  'order',
  'gain',
  'inform',
  'beaumont',
  'perform',
  'numer',
  'experi',
  'st',
  'martin',
  'period',
  'year',
  'experi',
  'uncomfort',
  'man',
  'insert',
  'bit',
  'differ',
  'food',
  'tie',
  'string',
  'hole',
  'stomach',
  'pull',
  'period',
  'observ',
  'digest',
  'beaumont',
  'remov',
  'gastric',
  'juic',
  'examin',
  'better',
  'understand',
  'natur',
  'beaumont',
  'father',
  'gastric',
  'physiolog',
  'find',
  'publish',
  'book',
  'experi',
  'observ',
  'gastric',
  'juic',
  'physiolog',
  'digest',
  '1833',
  'work',
  'consid',
  'basi',
  'earli',
  'knowledg',
  'digest',
  'william',
  'beaumont',
  'discov',
  'hydrochlor',
  'acid',
  'main',
  'chemic',
  'respons',
  'break',
  'food',
  'suggest',
  'import',
  'digest',
  'chemic',
  'known',
  'pepsin',
  'suggest',
  'digest',
  'chemic',
  'process',
  'mere',
  'mechan',
  'caus',
  'stomach',
  'muscl',
  'movement',
  'beaumont',
  'gave',
  'insight',
  'emot',
  'temperatur',
  'physic',
  'activ',
  'affect',
  'digest',
  'beaumont',
  'famou',
  'patient',
  'st',
  'martin',
  'outliv',
  'scientist',
  'wound',
  'complet',
  'heal',
  'children',
  'die',
  'age',
  '83',
  '2',
  'yovisto',
  'interest',
  'video',
  'lectur',
  'digest',
  'system']}

In [19]:
print("Número de documentos:", len(documents))
documentos_sin_tokens = [
    document["id"]
    for document in documents
    if not document["tokens"]
]

print("Documentos sin tokens:", documentos_sin_tokens)
cantidad_tokens = [
    len(document["tokens"])
    for document in documents
]

print("Mínimo:", min(cantidad_tokens))
print("Máximo:", max(cantidad_tokens))
print("Promedio:", sum(cantidad_tokens) / len(cantidad_tokens))

Número de documentos: 331
Documentos sin tokens: []
Mínimo: 125
Máximo: 701
Promedio: 342.7794561933535

## Recuperación booleana usando índice invertido (BSII).

### Creacion indice inverso

In [20]:
def build_inverted_index(documents):
    """
    Esta función construye un índice invertido a partir de una lista de documentos.
    Cada documento es un diccionario que contiene un identificador único y una lista de tokens.
    Devuelve un diccionario donde las claves son los tokens y los valores son listas de identificadores de documentos que contienen ese token.
    
    Parameters:
    documents (list): Una lista de diccionarios, donde cada diccionario representa un documento y contiene un identificador único y una lista de tokens.
    Returns:
    dict: Un diccionario que representa el índice invertido, donde las claves son los tokens y
    los valores son listas de identificadores de documentos que contienen ese token.
    """
    index = {}
    for document in documents:
        document_id = document["id"]
        for token in document["tokens"]:
            if token not in index:
                index[token] = set()
            index[token].add(document_id)
    for token in index:
        index[token] = sorted(index[token])
    return index

inverted_index = build_inverted_index(documents)
tabla_indice = pd.DataFrame(
    [
        {
            "termino": termino,
            "documentos": ", ".join(sorted(documentos))
        }
        for termino, documentos in list(inverted_index.items())[:20]
    ]
)

display(tabla_indice)

      termino                                         documentos
0     william  d001, d009, d015, d028, d035, d055, d056, d069...
1    beaumont                                               d001
2       human  d001, d002, d007, d012, d032, d036, d046, d050...
3      digest                 d001, d049, d054, d102, d263, d314
4   physiolog  d001, d037, d046, d062, d113, d120, d133, d191...
5        imag  d001, d004, d008, d015, d017, d018, d020, d021...
6       sourc  d001, d015, d025, d033, d041, d045, d053, d080...
7      novemb  d001, d002, d003, d004, d005, d006, d007, d008...
8          21  d001, d032, d069, d072, d099, d102, d128, d138...
9        1785  d001, d026, d043, d074, d086, d184, d245, d288...
10   american  d001, d005, d008, d013, d024, d028, d030, d032...
11    surgeon  d001, d010, d046, d049, d054, d062, d073, d084...
12       born  d001, d002, d003, d005, d006, d007, d008, d009...
13       best  d001, d002, d005, d014, d026, d029, d030, d031...
14      known  d001, d002, d005, d006, d007, d008, d009, d010...
15     father  d001, d003, d005, d009, d014, d016, d017, d020...
16    gastric                                               d001
17     follow  d001, d002, d003, d006, d010, d012, d013, d014...
18   research  d001, d005, d013, d014, d018, d020, d021, d023...
19    lebanon                                               d001

In [21]:
inverted_index.keys()

dict_keys(['william', 'beaumont', 'human', 'digest', 'physiolog', 'imag', 'sourc', 'novemb', '21', '1785', 'american', 'surgeon', 'born', 'best', 'known', 'father', 'gastric', 'follow', 'research', 'lebanon', 'connecticut', 'physician', 'serv', 'mate', 'armi', 'war', '1812', 'open', 'privat', 'practic', 'plattsburgh', 'new', 'york', 'rejoin', '1819', 'station', 'fort', 'mackinac', 'island', 'michigan', 'earli', '1820', 'exist', 'protect', 'interest', 'fur', 'compani', 'refug', 'wound', '19', 'year', 'old', 'french', 'canadian', 'trader', 'name', 'alexi', 'st', 'martin', 'shotgun', 'went', 'accid', 'store', 'close', 'rang', 'june', '6th', '1822', 'stomach', 'perfor', 'rib', 'broken', 'expect', 'young', 'man', 'surviv', 'skin', 'fuse', 'hole', 'leav', 'perman', 'fistula', '1', 'quickli', 'notic', 'potenti', 'system', 'order', 'gain', 'inform', 'perform', 'numer', 'experi', 'period', 'uncomfort', 'insert', 'bit', 'differ', 'food', 'tie', 'string', 'pull', 'observ', 'remov', 'juic', 'examin', 'better', 'understand', 'natur', 'find', 'publish', 'book', '1833', 'work', 'consid', 'basi', 'knowledg', 'discov', 'hydrochlor', 'acid', 'main', 'chemic', 'respons', 'break', 'suggest', 'import', 'pepsin', 'process', 'mere', 'mechan', 'caus', 'muscl', 'movement', 'gave', 'insight', 'emot', 'temperatur', 'physic', 'activ', 'affect', 'famou', 'patient', 'outliv', 'scientist', 'complet', 'heal', 'children', 'die', 'age', '83', '2', 'yovisto', 'video', 'lectur', 'selma', 'lagerlof', 'wonder', 'adventur', 'niel', 'holgersson', 'cover', 'nil', '20', '1858', 'swedish', 'author', 'nobel', 'laureat', 'femal', 'writer', 'win', 'prize', 'literatur', 'attend', 'teacher', 'colleg', 'stockholm', 'girl', 'secondari', 'school', 'landskrona', 'write', 'poetri', 'long', 'time', '1890', 'receiv', 'literari', 'competit', 'began', 'excerpt', 'popular', 'gosta', 'berl', 'saga', '1891', 'unnot', 'danish', 'translat', 'wide', 'critic', 'acclaim', 'pave', 'way', 'book‘', 'last', 'success', 'sweden', 'financi', 'support', 'royal', 'famili', 'academi', 'enabl', 'teach', 'focu', 'travel', 'itali', 'miracl', 'antichrist', '1897', 'jerusalem', '1900', 'belong', 'underbara', 'resa', 'genom', 'sverig', '1906', 'start', 'take', 'delight', 'hurt', 'anim', 'farm', 'boy', 'catch', 'tomt', 'church', 'refus', 'let', 'free', 'turn', 'shrunken', 'abl', 'talk', 'tini', 'seek', 'reveng', 'wild', 'gees', 'fli', 'white', 'goos', 'attempt', 'join', 'hold', 'bird', 'neck', 'pleas', 'domest', 'accomplish', 'task', 'accept', 'group', 'learn', 'chang', 'regular', 'size', 'good', 'stori', 'pictur', 'plain', 'scania', 'print', 'revers', 'krona', 'banknot', 'film', 'adapt', 'produc', 'world', 'seri', 'pixar', 'comput', 'ferdinand', 'de', 'lessep', 'suez', 'canal', 'mari', 'vicomt', '1805', '1894', 'diplomat', 'later', 'develop', 'construct', 'lessep‘', 'supervis', '1869', 'mediterranean', 'red', 'sea', 'substanti', 'reduc', 'sail', 'distanc', 'west', 'east', 'versail', 'yvelin', 'career', 'spent', 'occupi', 'consular', 'duti', 'educ', 'henri', 'iv', 'pari', '18', 'employ', 'commissari', 'depart', '1825', '1827', 'act', 'assist', 'vice', 'consul', 'lisbon', 'uncl', 'barthelemi', 'charg', 'd’affair', 'companion', 'explor', 'jean', 'francoi', 'la', 'perous', 'survivor', 'expedit', 'perish', 'profess', 'post', 'tunisia', 'egypt', '1832', 'appoint', 'alexandria', 'fortun', 'mehemet', 'ali', 'viceroy', 'owe', 'posit', 'recommend', 'behalf', 'govern', 'mathieu', 'gener', 'colonel', 'warm', 'welcom', 'friend', 'son', 'said', 'pasha', 'fascin', 'cultur', 'middl', 'growth', 'western', 'european', 'trade', 'spain', '1849', 'retir', 'disagr', 'public', 'office.[1', '1854', 'immedi', 'return', 'given', 'soon', 'permiss', 'begin', 'inspir', 'read', 'napoleon‘', 'abandon', 'plan', 'allow', 'larg', 'ship', 'wish', 'directli', 'cut', 'journey', 'africa', '7', 'land', 'scheme', 'direct', 'drawn', 'surveyor', 'linant', 'bey', 'mougel', 'provid', 'commun', 'slightli', 'modifi', 'adopt', 'intern', 'commiss', 'engin', '1856.[2', 'compagni', 'universel', 'du', 'maritim', 'organ', 'end', '25', 'april', '1859', 'blow', 'pickax', 'port', 'overcom', 'continu', 'opposit', 'british', 'prevent', 'sultan', 'approv', 'stage', 'cousin', 'empress', 'eugeni', 'persuad', 'emperor', 'napoleon', 'iii', 'arbitr', 'disput', 'final', '17', 'offici', 'khediv', 'ismail', 'despit', 'futil', 'trial', 'fail', 'project', 'attitud', 'seen', 'treat', 'great', 'celebr', 'subsequ', 'visit', 'britain', '1875', 'egyptian', 'sold', 'share', 'prime', 'minist', 'benjamin', 'disra', 'bought', 'effect', 'control', '74th', 'panama', '1879', 'congress', 'held', 'chose', 'rout', 'leader', 'undertak', 'decis', 'dig', 'level', 'avoid', 'use', 'lock', 'inabl', 'contemporari', 'medic', 'scienc', 'deal', 'epidem', 'malaria', 'yellow', 'fever', 'doom', 'declar', 'bankrupt', 'decemb', '1888', 'enter', 'liquid', 'februari', '1889', 'failur', 'refer', 'scandal', 'rumor', 'circul', 'politician', 'journalist', 'bribe', 'court', 'found', 'charl', 'guilti', 'mismanag', 'heavili', 'fine', 'sentenc', 'imprison', 'event', 'jail', 'paid', 'elderli', 'misjudg', 'prison', 'polit', '19th', 'centuri', 'imperi', 'zenith', 'prof', 'dr', 'thoma', 'w.', 'laqueur', 'univers', 'berkeley', 'bbc', 'histori', 'britannica', 'onlin', '3', 'associ', 'relat', 'articl', 'voyag', 'gustav', 'eiffel', 'tower', 'baron', 'haussmann', 'renov', 'oscar', 'niemey', 'visionari', 'architect', 'walt', 'disney', 'steamboat', 'willi', 'rise', 'mickey', 'mous', 'star', 'walk', 'fame', 'flickr', 'user', 'freshwater2006', '1928', 'movi', 'releas', 'present', 'charact', 'citi', 'notabl', 'cartoon', 'synchron', 'sound', 'black', 'debut', 'girlfriend', 'minni', 'distribut', 'steer', 'river', 'boat', 'real', 'captain', 'pete', 'appear', 'bridg', 'proceed', 'fight', 'forth', 'accident', 'trip', 'fall', 'eventu', 'board', 'mice', 'music', 'aboard', 'get', 'angri', 'peel', 'potato', 'parrot', 'make', 'fun', 'throw', 'knock', 'oswald', 'lucki', 'rabbit', 'person', 'lost', 'right', 'intend', 'silent', 'impress', 'audienc', 'distributor', 'came', 'realiz', 'ad', 'probabl', 'increas', 'appeal', 'dave', 'max', 'fleischer', 'inkwel', 'studio', 'mid', '1920', 'phonofilm', 'unfortun', 'click', 'track', 'musician', 'beat', 'meant', 'optic', 'mark', 'indic', 'precis', 'accompani', 'initi', 'doubt', 'arrang', 'test', 'screen', 'small', 'consist', 'employe', 'wive', 'live', 'partli', 'finish', 'bed', 'sheet', 'instal', 'microphon', 'speaker', 'mouth', 'percuss', 'special', 'like', 'bell', 'whistl', 'love', 'hire', 'profession', 'green', 'brother', 'novelti', 'band', 'soundtrack', 'premier', 'coloni', 'theater', 'instant', 'power', 'patrick', 'chappatt', 'eugen', 'wigner', 'structur', 'atom', 'nucleu', 'paul', '1902', '1995', 'hungarian', 'theoret', 'physicist', 'mathematician', 'contribut', 'theori', 'elementari', 'particl', 'particularli', 'discoveri', 'applic', 'fundament', 'symmetri', 'principl', '1963', 'maria', 'goeppert', 'thesi', 'bildung', 'und', 'zerfal', 'von', 'molekulen', 'format', 'decay', 'molecul', 'michael', 'polanyi', 'contain', 'rate', 'dissoci', 'have', 'doctor', 'budapest', 'tanneri', 'firm', 'thing', 'berlin', 'offer', 'karl', 'weissenberg', 'kaiser', 'wilhelm', 'institut', 'want', 'x', 'ray', 'crystallographi', 'request', 'arnold', 'sommerfeld', 'gottingen', 'david', 'hilbert', 'prove', 'disappoint', 'hilbert‘', 'shift', 'logic', 'nonetheless', 'studi', 'independ', 'laid', 'foundat', 'quantum', '1927', 'introduc', 'd', 'matrix', 'spend', 'term', 'princeton', 'saw', 'unit', 'state', '1930', '1933', 'vanish', 'nazi', 'rule', 'pass', '1936', '1938', 'wisconsin', 'rest', 'princeton.[2', '1937', 'citizen', '1939', 'leo', 'szilard', 'albert', 'einstein', 'meet', 'result', 'letter', 'urg', 'presid', 'franklin', 'd.', 'roosevelt', 'manhattan', 'bomb', 'led', 'team', 'design', 'product', 'nuclear', 'reactor', 'convert', 'uranium', 'weapon', 'gradeplutonium', 'paper', 'gone', 'july1942', 'conserv', '100', 'mw', 'graphit', 'neutron', 'moder', 'water', 'cool', 'chicago', 'pile', 'cp-1', 'achiev', 'chain', 'reaction', '1942', '1946', 'director', 'clinton', 'laboratori', 'oak', 'ridg', 'nation', 'tenn', 'administr', 'background', 'tempera', 'left', 'university.[3', 'award', 'mayer', 'german', 'j.', 'han', 'jensen', 'possibl', 'occur', 'newspap', 'wick', 'won', 'enrico', 'fermi', '1958', 'medal', '1969', 'near', 'life', 'thought', 'philosoph', 'vedanta', 'philosophi', 'hinduism', 'idea', 'pervad', 'conscious', 'januari', 'enjoy', 'short', 'tyler', 'dewitt', 'eugenio', 'beltrami', 'non', 'euclidian', 'geometri', '1835', '16', 'italian', 'concern', 'differenti', 'mathemat', 'note', 'especi', 'clariti', 'exposit', 'euclidean', 'model', 'surfac', 'constant', 'curvatur', 'pseudospher', 'cremona', 'lombardi', 'austrian', 'empir', 'artist', 'paint', 'miniatur', 'certainli', 'inherit', 'talent', 'case', 'addit', 'acquir', 'musicrath', 'pavia', '1853', 'expel', 'ghislieri', '1856', 'opinion', 'taught', 'influenc', 'francesco', 'brioschi', 'professor', 'appli', 'discontinu', 'hardship', 'secretari', 'venic', 'railroad', 'verona', 'milan', 'kingdom', 'establish', '1861', 'invigor', 'academ', 'scene', 'hard', '1862', 'bologna', '1870', 'rome', 'set', 'capit', 'chair', 'ration', '1873', 'move', 'there.[1', 'accademia', 'dei', 'lincei', '1898', 'senat', 'lover', 'relationship', 'music.[2', 'm.c.escher', 'circl', 'limit', 'illustr', 'hyperbol', '1868', 'memoir', 'interpret', 'bolyai', 'lobachevski', 'propos', 'neg', 'concept', 'line', 'repres', 'geodes', 'theorem', 'ordinari', 'dimension', 'space', 'deriv', 'axiomat', 'fashion', 'previous', '1840', 'mind', 'triangl', 'remark', 'correspond', 'trigonometr', 'formula', 'obtain', 'spheric', 'trigonometri', 'replac', 'usual', 'function', 'second', 'abstract', 'proof', 'equiconsist', 'dimens', 'klein', 'poincar', 'disk', 'half', 'plane', 'transform', 'today', 'essay', 'recogn', 'recept', 'enthusiast', 'thermodynam', 'elast', 'electr', 'magnet', 'topic', 'volum', 'oper', 'matematich', 'posthum', 'n.', 'wildberg', 'mathhist12', 'bernard', 'mandevil', 'fabl', 'bee', '15', '1670', 'dutch', 'economist', 'satirist', 'satir', 'key', 'econom', 'includ', 'divis', 'labor', 'invis', 'hand', 'seventi', 'thoroughli', 'elucid', 'adam', 'smith', 'grew', 'rotterdam', 'netherland', 'enrol', 'leiden', 'brutorum', 'operationibu', '1689', 'advoc', 'cartesian', 'automat', 'degre', 'medicin', '1691', 'titl', 'chylosi', 'vitiata', 'respect', 'grumbl', 'hive', '1705', '1714', 'benefit', 'mention', 'poem', 'detail', 'discuss', 'labour', 'describ', 'suddenli', 'honest', 'virtuou', 'be', 'collaps', 'lack', 'desir', 'explain', 'necessari', 'prosper', 'point', 'view', 'express', 'individu', 'collect', 'action', 'lead', 'believ', 'self', 'co', 'need', 'garner', 'ensur', 'peopl', 'passion', 'day', 'degrad', 'wealth', 'jame', 'paradi', 'baekeland', 'plastic', 'bakelit', 'billiard', 'ball', 'heritag', '14', '1863', 'belgian', 'chemist', 'henricu', 'arthur', 'invent', 'inexpens', 'nonflamm', 'versatil', 'modern', 'industri', 'ghent', 'chemistri', 'england', 'scotland', 'germani', 'stay', 'photograph', 'suppli', 'hous', 'velox', 'improv', 'gaslight', 'sunlight', 'kodak', 'maintain', 'home', 'nathaniel', 'thurlow', 'knew', 'phenol', 'formaldehyd', 'resin', 'adolf', 'baeyer', 'werner', 'kleeberg', 'report', 'mix', 'common', 'disinfect', 'form', 'insolubl', 'materi', 'ruin', 'equip', 'substanc', 'amorph', 'mass', 'infus', 'littl', 'luft', 'creat', 'commerci', 'viabl', 'mold', 'compound', 'fiber', 'coat', 'adhes', 'woven', 'fabric', 'polym', 'molecular', 'investig', 'novolak', 'binder', 'asbesto', 'manag', 'care', 'pressur', 'intermedi', 'reagent', 'moldabl', 'certain', 'filler', '1,2', 'advantag', 'extraordinarili', 'high', 'resist', 'emerg', 'automobil', 'integr', 'area', 'jewelleri', 'telephon', 'diana', 'cohen', 'tough', 'truth', 'pollut', 'dorothea', 'erxleben', 'christian', '1715', '1762', '13', 'prejudic', 'proper', 'wors', '1901', 'woman', 'exam', 'aschersleben', 'show', 'smart', 'give', 'latin', 'class', 'scientif', 'aim', 'wrote', 'frederick', 'advis', 'hall', 'admit', 'student', 'hometown', 'formal', 'accus', 'amateur', 'situat', 'shame', 'women', 'freeli', 'men', 'offic', 'rais', 'treatment', 'dilettant', 'decid', 'dissert', '1755', 'quod', 'nimi', 'cito', 'ac', 'iucund', 'curar', 'saepiu', 'fiat', 'causa', 'minu', 'tuta', 'curationi', 'pharmaceut', '1899', 'hospit', 'play', 'written', 'away', 'susann', 'sir', 'simpson', 'chloroform', '1st', 'baronet', '1811', '12', '1847', 'scottish', 'obstetrician', 'figur', 'anesthet', 'pain', 'se', 'excess', 'destruct', 'ultim', 'fatal', 'bathgat', 'edinburg', 'lothian', 'seventh', 'eighth', 'child', 'impecuni', 'baker', 'edinburgh', 'graduat', 'wait', 'got', 'licens', '1838', 'air', 'tractor', 'earliest', 'vacuum', 'extractor', 'childbirth', 'method', 'ventous', '28', 'midwiferi', 'pioneer', 'obstetr', 'gynecolog', 'forcep', 'ignaz', 'semmelwei', 'fought', 'contagion', 'puerper', 'sepsi', 'introduct', 'anaesthesia', 'unlik', 'suffer', 'search', 'allevi', 'london', 'met', 'robert', 'lister', 'prais', 'ether', 'recent', '1799', 'humphri', 'davi', 'nitrou', 'oxid', 'laugh', 'ga', 'anaesthet', 'conduc', 'compounds.[3', 'queen', 'victoria', 'properti', 'keith', 'duncan', 'sit', 'even', 'dine', 'room', 'tri', '4', 'ponder', 'ignor', 'inhal', 'mood', 'cheer', 'humour', 'regain', 'morn', 'woke', 'chanc', 'dosag', 'administ', 'danger', 'fact', 'util', 'eas', 'oppos', 'tamper', 'divin', 'accord', 'genesi', 'lord', 'punish', 'womankind', 'eve', 'eat', 'appl', 'tree', 'controversi', 'surround', 'disappear', 'help', 'deliv', 'princ', 'leopold', '1853.[3', 'extend', 'uterin', 'wire', 'sutur', 'statist', 'analysi', 'outcom', 'fetal', 'patholog', 'hermaphrodit', 'field', 'archeolog', 'honour', '1866', '59', 'funer', 'mourn', 'thousand', 'hears', 'street', '30,000', 'mourners.[2', 'watch', 'ted', 'stuart', 'hameroff', 'clinic', 'anesthesiologist', 'select', 'eras', 'delic', 'protein', 'dynam', 'soul', 'implic', 'bodi', 'loui', 'antoin', 'bougainvil', 'reach', 'tahiti', '11', '1729', 'admir', 'cook', 'record', 'settlement', 'falkland', 'pacif', 'ocean', 'largest', 'solomon', 'color', 'tropic', 'climb', 'plant', 'bougainvillaea', 'law', 'shortli', '1753', 'sent', 'embassi', 'seven', 'particip', 'defens', 'quebec', 'negoti', 'treati', 'conced', 'franc', 'colon', 'expens', '1763', 'eagl', 'sphinx', 'bay', '1764', 'circumnavig', 'globe', '1760', 'assum', 'carri', 'naturalist', 'geograph', 'crew', 'boudeus', '214', 'etoil', '116', 'botanist', 'philibert', 'commercon', 'flower', 'bougainvillea', 'jeann', 'baret', 'disguis', 'call', 'enlist', 'valet', 'otaheit', 'westward', 'southern', 'samoa', 'hebrid', 'barrier', 'reef', 'attack', 'ireland', 'head', 'molucca', 'mission', 'loss', '1770', 'log', 'le', 'autour', 'mond', 'par', 'fregat', 'et', 'flute', 'l’etoil', 'biolog', 'anthropolog', 'argentina', 'patagonia', 'indonesia', 'jim', 'bennett', 'morison', 'classif', '1620', '1683', '10', 'taxonomist', 'forerunn', 'john', 'systemat', 'aberdeen', 'wife', 'anna', 'gray', 'outstand', 'scholar', 'master', 'art', 'ph.d', 'eighteen', 'devot', 'hebrew', 'parent', 'ministri', 'english', 'civil', 'royalist', 'cavali', 'serious', 'battl', 'dee', 'recov', 'fled', 'appar', 'anatomi', 'zoolog', 'botani', 'mineralog', 'theophrastu', 'dioscorid', '1648', 'took', 'anger', 'entir', 'tutor', 'vespasian', 'robin', 'king', 'household', 'gaston', 'duke', 'orlean', '1649', '1650', 'colleagu', 'abel', 'bruyner', 'nichola', 'marchant', 'keeper', 'garden', 'bloi', 'years.[1', 'montpelli', 'fontainebleau', 'burgundi', 'poitou', 'brittani', 'languedoc', 'provenc', 'patron', '1660', 'induc', 'invit', 'newli', 'restor', 'ii', 'oxford', '1669', 'reviv', 'press', 'hortu', 'regiu', 'blesensi', 'catalogu', 'descript', '260', 'un', 'varieti', 'plantarum', 'umbelliferarum', 'distributio', 'nova', '1672', 'praeludia', 'botanica', 'stress', 'fruit', 'focus', 'habitat', 'obviou', 'botan', 'prefac', 'definit', 'statement', 'monograph', 'specif', 'umbellifera', 'carrot', 'parsley', 'apiacea', 'identifi', 'rembert', 'dodoen', 'distinct', '1583', 'base', 'seed', 'characterist', 'supplement', 'veget', 'featur', 'divid', 'umbel', 'type', 'infloresc', 'genera', 'true', 'umbellif', 'umbella', 'impropri', 'dicto', 'valeriana', 'filipendula', 'thalictrum.[2', 'drew', 'schema', 'debt', 'andrea', 'cesalpino', 'carl', 'linneau', '1737', 'vain', 'suffici', 'expir', 'look', 'tournefort', 'readili', 'indebt', 'conscienti', 'taken', 'guidanc', 'wander', 'pursuit', 'affin', 'injur', 'pole', 'carriag', 'cross', '9', 'nov', 'livelihood', 'depend', 'kew', 'millennium', 'bank', 'florenc', 'sabin', 'prepar', 'ground', '1871', '1953', 'rena', 'professorship', 'hopkin', 'elect', 'rockefel', 'colorado', 'patern', 'grandpar', 'vermont', 'earn', 'bachelor', '1893', 'mall', 'skill', 'anatomist', 'involv', 'build', 'reput', '3d', 'newborn', 'babi', 'brainstem', 'textbook', 'atla', 'medulla', 'midbrain', 'embryolog', 'lymphat', 'embryo', 'blood', 'vessel', 'fellowship', 'histolog', '1917', 'lifetim', 'member', 'origin', 'cell', 'brain', 'immunolog', 'tuberculosi', 'cellular', 'health', 'reveal', 'bad', 'uninterest', 'effort', 'reward', 'bill', 'chariti', 'denver', 'donat', 'salari', 'octob', 'visual', 'data', 'explos', 'ander', 'ynnerman', 'hermann', 'kleck', 'rorschach', 'eponym', 'tenth', 'blot', 'inkblot', '8', '1884', 'swiss', 'freudian', 'psychiatrist', 'psychoanalyst', 'reportedli', 'reflect', 'unconsci', 'part', 'stimuli', 'zurich', 'switzerland', 'encourag', 'creativ', 'kind', 'klecksographi', 'classmat', 'sure', 'difficulti', 'ask', 'ernst', 'haeckel', 'neuchatel', '1904', 'geolog', 'universit', 'dijon', 'bern', 'psycholog', 'nuremberg', 'combin', 'imageri', 'justinu', 'kerner', '1857', 'alfr', 'binet', 'measur', 'schizophren', 'version', 'schizophrenia', '1921', 'late', 'samuel', 'beck', 'bruno', 'klopfer', 'expand', 'scope', 'psychologist', 'judgement', 'broad', 'trait', 'skeptic', 'valu', 'assess', '1922', '37', '1960', 'rank', 'list', 'outpati', 'mental', 'primari', 'courtroom', 'custodi', 'issu', 'determin', 'elig', 'parol', 'glenn', 'wilson', 'profil', 'killer', 'stukeley', 'mysteri', 'stoneheng', 'photo', 'wikipedia', '1687', 'antiquarian', 'anglican', 'clergyman', 'archaeolog', 'prehistor', 'monument', 'aveburi', 'rememb', 'disciplin', 'biograph', 'isaac', 'newton', 'holbeach', 'lincolnshir', 'lawyer', 'm.b', 'corpu', 'christi', 'cambridg', 'topograph', 'architectur', 'draw', 'sketch', 'histor', 'artefact', '1710', 'boston', 'spald', 'gentlemen', 'societi', '1717', 'fellow', '1718', 'antiquari', '1719', 'm.d', '1720', 'predecessor', 'druid', 'tho', 'extremest', 'advanc’d', 'inquiri', 'disadvantag', 'height', 'asham’d', 'wink', 'sunshin', 'religion', 'templ', 'restor’d', '1740)[2', 'inward', 'august', '1722', 'account', 'aubrey', '70', 'particular', 'survey', 'map', 'burial', 'earthwork', 'princip', 'elabor', '1740', '1743', 'suppos', 'multi', 'pre', 'roman', 'site', 'built', 'celt', 'priest', 'specul', 'evid', 'ancient', 'text', 'conclud', 'phoenician', 'colonist', 'arriv', 'romant', 'fictiti', 'vision', 'worship', 'cult', 'patriarchi', 'mankind', 'degener', 'idol', 'exampl', 'interestingli', '18th', 'perceiv', 'landscap', 'sacr', 'pattern', 'centr', 'stone', 'larger', 'inscrib', 'serpent', 'dragon', 'variant', 'creatur', 'worm', 'countrysid', 'link', 'local', 'legend', 'place', 'coincid', 'sanctity.[3', 'date', 'renown', 'astronom', 'edmund', 'halley', 'builder', 'align', 'north', 'incomplet', 'variat', 'theoriz', 'excel', 'archaeologist', 'remain', 'extens', 'itinerarium', 'curiosum', '1724observ', 'itinerari', 'attract', 'freemasonri', '1752', 'actual', 'formul', 'gravit', 'prolif', 'poet', 'numismatist', 'genealogist', 'death', '1765', 'willett', 'oti', 'adolph', 'sax', 'saxophon', '1814', '6', 'instrument', 'joseph', 'clarinet', 'footnot', 'creation', 'forgotten', 'jazz', 'bare', 'name.[2', 'dorm', 'semest', 'tell', 'listen', 'beginn'

In [22]:
memoria_indice = sys.getsizeof(inverted_index)

for termino, postings in inverted_index.items():
    memoria_indice += sys.getsizeof(termino)
    memoria_indice += sys.getsizeof(postings)

    for documento in postings:
        memoria_indice += sys.getsizeof(documento)

print("Número de documentos:", len(documents))
print("Tamaño del vocabulario:", len(inverted_index))
print("Memoria aproximada del índice:", memoria_indice, "bytes")

Número de documentos: 331
Tamaño del vocabulario: 13923
Memoria aproximada del índice: 6216254 bytes

In [23]:
termino_mas_frecuente = None
termino_menos_frecuente = None

max_postings = 0
min_postings = None

for termino, postings in inverted_index.items():
    cantidad_postings = len(postings)

    if cantidad_postings > max_postings:
        max_postings = cantidad_postings
        termino_mas_frecuente = termino

    if min_postings is None or cantidad_postings < min_postings:
        min_postings = cantidad_postings
        termino_menos_frecuente = termino

print("Término más frecuente:", termino_mas_frecuente)
print("Número de postings:", max_postings)

print("Término menos frecuente:", termino_menos_frecuente)
print("Número de postings:", min_postings)

Término más frecuente: yovisto
Número de postings: 320
Término menos frecuente: beaumont
Número de postings: 1

### Consultas booleanas


Sin *skip pointers*, la intersección tiene complejidad $O(m+n)$ ya que el algortimo que se usa es un *merge* de las listas de postings asociadas a los terminos. Con *skip pointers* se pueden reducir las comparaciones  procesando las intersecciones en menos tiempo al saltar segmentos que no pueden producir coincidencias; sin embargo, el beneficio depende de la distribución y longitud de las listas, por lo que no debe asumirse una mejora asintótica fija para todos los casos. En este caso, tomando $\sqrt{p}$ *skip pointers* distribuidos uniformemente, en el mejor de los casos la complejidad se reduce a:


$$
O(\sqrt{m} + \sqrt{n})
$$


Los skip pointers no son útiles para las consultas OR, ya que en este caso no buscamos únicamente documentos que aparezcan en ambas listas, sino que necesitamos conservar todos los documentos presentes en cualquiera de ellas, eliminando solamente los repetidos. Por esta razón, saltar posiciones mediante skip pointers podría hacer que se omitan documentos que deberían formar parte del resultado.

In [24]:
def build_skip_pointers(postings):
    """
    Construye punteros de salto para una lista de postings.

    Los punteros de salto aprovechan la estructura ordenada de los
    postings para permitir saltos durante la intersección de listas,
    mejorando la eficiencia de las búsquedas.

    La longitud del salto se determina utilizando la raíz cuadrada
    del tamaño de la lista de postings.

    Parameters:
        postings (list): Lista ordenada de identificadores de documentos.

    Returns:
        dict: Diccionario donde las claves son los índices de los
            postings y los valores son los índices de destino de los saltos.
    """
    skips = {}
    skip_length = int(math.sqrt(len(postings)))
    if skip_length < 2:
        return skips

    for i in range(0, len(postings) - skip_length, skip_length):
        skips[i] = i + skip_length

    return skips


def intersect_without_skips(postings1, postings2):
    """ 
    Compara dos lista: postings1 y postings2 a partir de punteros mientras existan elementos que comparar en ambas listas. 
    Iteración i y j sean menores a la cantidad de obtenos dentro del posting 1 y 2 respectivamente. 

    La función va contando las comparaciones y consolidando las intersecciones en result.

    Parameters:
        postings1: Lista de documentos ordenados en los que aparece un termino dado 
        postings2: Lista de documentos ordenados en los que aparece el termino comparable 

    Returns:
        result: Lista de documentos ordenados en los que aparecen ambos terminos
        comparisons: Número de comparaciones realizadas para evaluar el consumo sin punteros de salto.   

    """
    result = []
    comparisons = 0
    i = 0
    j = 0
    while i < len(postings1) and j < len(postings2):
        comparisons += 1
        if postings1[i] == postings2[j]:
            result.append(postings1[i])
            i += 1
            j += 1
        elif postings1[i] < postings2[j]:
            i += 1
        else:
            j += 1
    return result, comparisons

def union_postings(postings1, postings2):
    """
    Esta función une los documentos de los postings garantizando la no duplicidad de los mismos.
    Sirve para responder querys de OR. En donde se espera el retorno de documentos con al menos uno de los terminos consultados.


    Parameters:
        postings1: Lista de documentos ordenados en los que aparece un termino dado 
        postings2: Lista de documentos ordenados en los que aparece el termino comparable 
        
    Returns:
        result: Lista de todos documentos ordenados sin duplicados.
    """
    result = []
    i = 0
    j = 0
    while i < len(postings1) and j < len(postings2):
        if postings1[i] == postings2[j]:
            result.append(postings1[i])
            i += 1
            j += 1
        elif postings1[i] < postings2[j]:
            result.append(postings1[i])
            i += 1
        else:
            result.append(postings2[j])
            j += 1
    while i < len(postings1):
        result.append(postings1[i])
        i += 1

    while j < len(postings2):
        result.append(postings2[j])
        j += 1

    return result

def not_postings(postings, documents):
    """
    Esta función busca entregar los documentos que no contienen al termino.
    
    Parameters:
        postings: Lista de documentos ordenados en los que aparece un termino dado.
        documents: Lista de documentos del corpus
    
    Returns:
        result: Lista de documenos ordenados que no contienen el termino.

    """
    result = []
    documentos_postings = set(postings)
    for document in documents:
        if document["id"] not in documentos_postings:
            result.append(document["id"])
    result.sort()
    return result

def intersect_with_skips(postings1, postings2, skips1, skips2):
    """Calcula la intersección de dos listas de postings ordenadas utilizando skip pointers para mejorar la eficiencia de la búsqueda.

    Durante la intersección, compara los documentos de ambas listas mediante dos punteros.
    Cuando el documento de una lista es menor que el de la otra, intenta utilizar un skip pointer para avanzar varias posiciones.
    El salto solo se realiza si su documento de destino no supera el documento actual de la otra lista, evitando así omitir posibles coincidencias.

    Parameters:
        postings1: Primera lista de identificadores de documentos, ordenada de forma ascendente.
        postings2: Segunda lista de identificadores de documentos, ordenada de forma ascendente.
        skips1: Diccionario de skip pointers para postings1. Las claves son índices de la lista y los valores son los índices de destino del salto.
        skips2: Diccionario de skip pointers para postings2. Las claves son índices de la lista y los valores son los índices de destino del salto.

    Returns:
        tuple: Una tupla con tres elementos:
            - result (list): Lista ordenada de documentos presentes en ambas posting lists.
            - comparisons (int): Número de comparaciones realizadas durante la intersección.
            - skips_used (int): Número de skip pointers utilizados."""
    result = []
    comparisons = 0
    skips_used = 0
    i = 0
    j = 0
    while i < len(postings1) and j < len(postings2):
        comparisons += 1
        if postings1[i] == postings2[j]:
            result.append(postings1[i])
            i += 1
            j += 1
        elif postings1[i] < postings2[j]:
            if (i in skips1 and postings1[skips1[i]] <= postings2[j]):
                i = skips1[i]
                skips_used += 1
            else:
                i += 1
        else:
            if (j in skips2 and postings2[skips2[j]] <= postings1[i]):
                j = skips2[j]
                skips_used += 1
            else:
                j += 1
    return result, comparisons, skips_used

### Evaluacion Queries

#### Consulta booleana

In [25]:
def split_boolean_query(query):
    """
    Divide una consulta booleana en tokens individuales, separando explícitamente los paréntesis para facilitar su posterior procesamiento.

    Parameters:
        query (str): Consulta booleana ingresada como una cadena de texto. Puede contener términos, operadores booleanos (AND, OR, NOT) y paréntesis.

    Returns:
        list: Lista de tokens obtenidos a partir de la consulta."""
    query = query.replace("(", " ( ")
    query = query.replace(")", " ) ")

    return query.split()

def process_boolean_tokens(tokens):
    """Preprocesa los tokens de una consulta booleana antes de evaluarla.

    Los operadores booleanos y los paréntesis se conservan sin modificar.
    Los términos de búsqueda se limpian, normalizan, tokenizan, filtran
    para eliminar signos de puntuación y palabras vacías, y finalmente
    se reducen mediante stemming para que sean compatibles con los
    términos utilizados en el índice invertido.

    Parameters:
        tokens (list): Lista de tokens obtenidos a partir de una consulta
            booleana.

    Returns:
        list: Lista de tokens procesados, conservando los operadores
            booleanos y paréntesis."""
    
    result = []
    operators = ["AND", "OR", "NOT", "(", ")"]
    for token in tokens:
        if token in operators:
            result.append(token)
        else:
            content = clean_text(token)
            contentN = normalize_text(content, True)
            processed_tokens = [ t.text for t in nlp(contentN) if not t.is_punct and not t.is_stop]
            for processed_token in processed_tokens:result.append(stemmer.stem(processed_token))
    return result

def parse_not(tokens, position):
    """Evalúa expresiones que contienen operadores NOT, términos individuales
    o expresiones agrupadas mediante paréntesis.

    El operador NOT se evalúa de forma recursiva y obtiene el complemento
    de la posting list correspondiente respecto al conjunto de documentos.
    Cuando encuentra un paréntesis, delega la evaluación de la expresión
    interna al parser de OR.

    Parameters:
        tokens (list): Lista de tokens de la consulta booleana procesada.
        position (int): Posición actual dentro de la lista de tokens.

    Returns:
        tuple: Una tupla formada por:
            - result (list): Posting list resultante de la expresión evaluada.
            - position (int): Posición del siguiente token que debe ser
              procesado."""
    
    if tokens[position] == "NOT":
        result, position = parse_not(tokens, position + 1)
        return not_postings(result, documents), position
    if tokens[position] == "(":
        result, position = parse_or(tokens, position + 1)
        return result, position + 1
    return inverted_index.get(tokens[position], []), position + 1

def parse_and(tokens, position):
    """Evalúa expresiones booleanas que contienen el operador AND.

    Obtiene inicialmente una expresión mediante parse_not y posteriormente
    realiza intersecciones sucesivas cuando encuentra operadores AND.
    Para cada intersección construye skip pointers para ambas posting lists
    y utiliza dichos punteros para mejorar la eficiencia de la intersección.

    Parameters:
        tokens (list): Lista de tokens de la consulta booleana procesada.
        position (int): Posición actual dentro de la lista de tokens.

    Returns:
        tuple: Una tupla formada por:
            - result (list): Posting list resultante de la intersección.
            - position (int): Posición del siguiente token que debe ser
              procesado."""
    
    result, position = parse_not(tokens, position)
    while position < len(tokens) and tokens[position] == "AND":
        next_result, position = parse_not(tokens, position + 1)
        skips1 = build_skip_pointers(result)
        skips2 = build_skip_pointers(next_result)
        result, _, _ = intersect_with_skips(result, next_result, skips1, skips2)
    return result, position

def parse_or(tokens, position):
    """Evalúa expresiones booleanas que contienen el operador OR.

    Obtiene inicialmente una expresión mediante parse_and y posteriormente
    realiza uniones sucesivas cuando encuentra operadores OR. La función
    delega la evaluación de las expresiones AND a parse_and, estableciendo
    así la precedencia de AND sobre OR.

    Parameters:
        tokens (list): Lista de tokens de la consulta booleana procesada.
        position (int): Posición actual dentro de la lista de tokens.

    Returns:
        tuple: Una tupla formada por:
            - result (list): Posting list resultante de la unión.
            - position (int): Posición del siguiente token que debe ser
              procesado."""
    result, position = parse_and(tokens, position)
    while position < len(tokens) and tokens[position] == "OR":
        next_result, position = parse_and(tokens, position + 1)
        result = union_postings(result, next_result)
    return result, position

def evaluate_boolean_query(tokens):
    """Evalúa una consulta booleana completa a partir de sus tokens procesados.

    Inicia el análisis sintáctico desde la primera posición de la consulta
    utilizando parse_or, que a su vez coordina la evaluación de las
    expresiones AND, OR, NOT y los paréntesis.

    Parameters:
        tokens (list): Lista de tokens de una consulta booleana procesada.

    Returns:
        list: Lista ordenada de identificadores de los documentos que
            satisfacen la consulta booleana."""
    result, _ = parse_or(tokens, 0)
    return result

In [26]:

process_boolean_tokens(split_boolean_query("river AND (french OR method)"))

['river', 'AND', '(', 'french', 'OR', 'method', ')']

In [27]:
pruebas = [
    "river AND french",
    "river OR french",
    "NOT river",
    "river AND NOT french",
    "river OR NOT french",
    "river OR french AND method",
    "river AND (french OR method)",
    "(river OR french) AND method"
]

for query in pruebas:
    tokens = split_boolean_query(query)
    tokens = process_boolean_tokens(tokens)

    resultado = evaluate_boolean_query(tokens)

    print(query)
    print("Tokens:", tokens)
    print("Cantidad:", len(resultado))
    print("Resultado:", resultado)
    print()

river AND french
Tokens: ['river', 'AND', 'french']
Cantidad: 7
Resultado: ['d029', 'd053', 'd096', 'd184', 'd189', 'd257', 'd313']

river OR french
Tokens: ['river', 'OR', 'french']
Cantidad: 94
Resultado: ['d001', 'd003', 'd004', 'd011', 'd012', 'd014', 'd019', 'd025', 'd026', 'd029', 'd035', 'd038', 'd042', 'd047', 'd052', 'd053', 'd056', 'd063', 'd066', 'd074', 'd075', 'd078', 'd083', 'd085', 'd090', 'd095', 'd096', 'd099', 'd101', 'd105', 'd108', 'd109', 'd111', 'd120', 'd122', 'd126', 'd135', 'd138', 'd139', 'd140', 'd141', 'd145', 'd147', 'd148', 'd150', 'd152', 'd157', 'd160', 'd162', 'd164', 'd166', 'd167', 'd168', 'd170', 'd181', 'd184', 'd185', 'd188', 'd189', 'd190', 'd191', 'd202', 'd212', 'd231', 'd232', 'd235', 'd236', 'd237', 'd242', 'd246', 'd248', 'd252', 'd257', 'd263', 'd264', 'd265', 'd268', 'd280', 'd281', 'd283', 'd285', 'd288', 'd293', 'd302', 'd304', 'd309', 'd313', 'd317', 'd323', 'd324', 'd325', 'd327', 'd330', 'd331']

NOT river
Tokens: ['NOT', 'river']
Cantidad: 305
Resultado: ['d001', 'd002', 'd003', 'd005', 'd006', 'd007', 'd008', 'd009', 'd010', 'd011', 'd012', 'd013', 'd014', 'd015', 'd016', 'd017', 'd018', 'd019', 'd020', 'd021', 'd022', 'd023', 'd024', 'd026', 'd027', 'd028', 'd030', 'd031', 'd032', 'd033', 'd034', 'd036', 'd037', 'd038', 'd039', 'd040', 'd041', 'd042', 'd043', 'd044', 'd045', 'd046', 'd047', 'd048', 'd049', 'd050', 'd051', 'd052', 'd054', 'd055', 'd056', 'd057', 'd058', 'd059', 'd060', 'd061', 'd062', 'd063', 'd064', 'd065', 'd066', 'd067', 'd068', 'd069', 'd070', 'd071', 'd072', 'd073', 'd074', 'd075', 'd076', 'd077', 'd079', 'd080', 'd081', 'd082', 'd083', 'd084', 'd085', 'd086', 'd087', 'd088', 'd089', 'd091', 'd092', 'd093', 'd094', 'd097', 'd098', 'd099', 'd100', 'd101', 'd102', 'd103', 'd104', 'd105', 'd106', 'd107', 'd108', 'd109', 'd110', 'd111', 'd112', 'd113', 'd114', 'd115', 'd116', 'd117', 'd118', 'd119', 'd120', 'd121', 'd122', 'd123', 'd124', 'd125', 'd126', 'd127', 'd128', 'd129', 'd130', 'd131', 'd132', 'd133', 'd134', 'd135', 'd136', 'd137', 'd140', 'd142', 'd143', 'd144', 'd145', 'd146', 'd147', 'd148', 'd149', 'd150', 'd151', 'd153', 'd154', 'd155', 'd156', 'd158', 'd159', 'd160', 'd161', 'd162', 'd163', 'd164', 'd165', 'd166', 'd167', 'd168', 'd169', 'd170', 'd171', 'd172', 'd173', 'd174', 'd175', 'd176', 'd177', 'd178', 'd179', 'd180', 'd181', 'd182', 'd183', 'd185', 'd186', 'd187', 'd188', 'd190', 'd192', 'd193', 'd194', 'd195', 'd196', 'd197', 'd198', 'd199', 'd200', 'd201', 'd202', 'd203', 'd204', 'd205', 'd206', 'd207', 'd208', 'd209', 'd210', 'd211', 'd212', 'd213', 'd214', 'd215', 'd216', 'd217', 'd218', 'd219', 'd220', 'd221', 'd222', 'd223', 'd224', 'd225', 'd226', 'd227', 'd228', 'd229', 'd230', 'd232', 'd233', 'd234', 'd235', 'd237', 'd238', 'd239', 'd240', 'd241', 'd242', 'd243', 'd244', 'd245', 'd246', 'd247', 'd248', 'd249', 'd250', 'd251', 'd252', 'd253', 'd254', 'd255', 'd256', 'd258', 'd259', 'd260', 'd261', 'd262', 'd263', 'd264', 'd266', 'd267', 'd268', 'd269', 'd270', 'd271', 'd272', 'd273', 'd274', 'd275', 'd276', 'd277', 'd278', 'd279', 'd281', 'd282', 'd283', 'd284', 'd285', 'd286', 'd287', 'd288', 'd289', 'd290', 'd291', 'd292', 'd293', 'd294', 'd295', 'd296', 'd297', 'd298', 'd299', 'd300', 'd301', 'd303', 'd304', 'd305', 'd306', 'd307', 'd308', 'd310', 'd311', 'd312', 'd314', 'd315', 'd316', 'd317', 'd318', 'd319', 'd320', 'd321', 'd322', 'd323', 'd324', 'd325', 'd326', 'd327', 'd328', 'd329', 'd330']

river AND NOT french
Tokens: ['river', 'AND', 'NOT', 'french']
Cantidad: 19
Resultado: ['d004', 'd025', 'd035', 'd078', 'd090', 'd095', 'd138', 'd139', 'd141', 'd152', 'd157', 'd191', 'd231', 'd236', 'd265', 'd280', 'd302', 'd309', 'd331']

river OR NOT french
Tokens: ['river', 'OR', 'NOT', 'french']
Cantidad: 263
Resultado: ['d002', 'd004', 'd005', 'd006', 'd007', 'd008', 'd009', 'd010', 'd013', 'd015', 'd016', 'd017', 'd018', 'd020', 'd021', 'd022', 'd023', 'd024', 'd025', 'd027', 'd028', 'd029', 'd030', 'd031', 'd032', 'd033', 'd034', 'd035', 'd036', 'd037', 'd039', 'd040', 'd041', 'd043', 'd044', 'd045', 'd046', 'd048', 'd049', 'd050', 'd051', 'd053', 'd054', 'd055', 'd057', 'd058', 'd059', 'd060', 'd061', 'd062', 'd064', 'd065', 'd067', 'd068', 'd069', 'd070', 'd071', 'd072', 'd073', 'd076', 'd077', 'd078', 'd079', 'd080', 'd081', 'd082', 'd084', 'd086', 'd087', 'd088', 'd089', 'd090', 'd091', 'd092', 'd093', 'd094', 'd095', 'd096', 'd097', 'd098', 'd100', 'd102', 'd103', 'd104', 'd106', 'd107', 'd110', 'd112', 'd113', 'd114', 'd115', 'd116', 'd117', 'd118', 'd119', 'd121', 'd123', 'd124', 'd125', 'd127', 'd128', 'd129', 'd130', 'd131', 'd132', 'd133', 'd134', 'd136', 'd137', 'd138', 'd139', 'd141', 'd142', 'd143', 'd144', 'd146', 'd149', 'd151', 'd152', 'd153', 'd154', 'd155', 'd156', 'd157', 'd158', 'd159', 'd161', 'd163', 'd165', 'd169', 'd171', 'd172', 'd173', 'd174', 'd175', 'd176', 'd177', 'd178', 'd179', 'd180', 'd182', 'd183', 'd184', 'd186', 'd187', 'd189', 'd191', 'd192', 'd193', 'd194', 'd195', 'd196', 'd197', 'd198', 'd199', 'd200', 'd201', 'd203', 'd204', 'd205', 'd206', 'd207', 'd208', 'd209', 'd210', 'd211', 'd213', 'd214', 'd215', 'd216', 'd217', 'd218', 'd219', 'd220', 'd221', 'd222', 'd223', 'd224', 'd225', 'd226', 'd227', 'd228', 'd229', 'd230', 'd231', 'd233', 'd234', 'd236', 'd238', 'd239', 'd240', 'd241', 'd243', 'd244', 'd245', 'd247', 'd249', 'd250', 'd251', 'd253', 'd254', 'd255', 'd256', 'd257', 'd258', 'd259', 'd260', 'd261', 'd262', 'd265', 'd266', 'd267', 'd269', 'd270', 'd271', 'd272', 'd273', 'd274', 'd275', 'd276', 'd277', 'd278', 'd279', 'd280', 'd282', 'd284', 'd286', 'd287', 'd289', 'd290', 'd291', 'd292', 'd294', 'd295', 'd296', 'd297', 'd298', 'd299', 'd300', 'd301', 'd302', 'd303', 'd305', 'd306', 'd307', 'd308', 'd309', 'd310', 'd311', 'd312', 'd313', 'd314', 'd315', 'd316', 'd318', 'd319', 'd320', 'd321', 'd322', 'd326', 'd328', 'd329', 'd331']

river OR french AND method
Tokens: ['river', 'OR', 'french', 'AND', 'method']
Cantidad: 45
Resultado: ['d004', 'd012', 'd025', 'd026', 'd029', 'd035', 'd042', 'd052', 'd053', 'd078', 'd085', 'd090', 'd095', 'd096', 'd099', 'd109', 'd122', 'd138', 'd139', 'd141', 'd152', 'd157', 'd170', 'd184', 'd189', 'd191', 'd202', 'd212', 'd231', 'd235', 'd236', 'd246', 'd257', 'd263', 'd265', 'd280', 'd281', 'd285', 'd288', 'd302', 'd309', 'd313', 'd327', 'd330', 'd331']

river AND (french OR method)
Tokens: ['river', 'AND', '(', 'french', 'OR', 'method', ')']
Cantidad: 9
Resultado: ['d029', 'd035', 'd053', 'd096', 'd184', 'd189', 'd231', 'd257', 'd313']

(river OR french) AND method
Tokens: ['(', 'river', 'OR', 'french', ')', 'AND', 'method']
Cantidad: 21
Resultado: ['d012', 'd026', 'd035', 'd042', 'd052', 'd085', 'd099', 'd109', 'd122', 'd170', 'd202', 'd212', 'd231', 'd235', 'd246', 'd263', 'd281', 'd285', 'd288', 'd327', 'd330']

####  ¿Cómo se compara el algoritmo de mezcla con y sin skip pointers para la consulta early AND telecommunication?

Para la consulta **`early AND telecommunication`**, ambos algoritmos recuperan los mismos documentos: `['d060', 'd100', 'd231']`. Sin embargo, el algoritmo **sin skip pointers** realiza **107 comparaciones**, mientras que el algoritmo **con skip pointers** realiza únicamente **41 comparaciones**, utilizando **6 saltos**. Esto representa una reducción de aproximadamente **61.7 % en el número de comparaciones**, mostrando que los *skip pointers* permiten evitar recorrer posiciones innecesarias de las listas de postings y hacen más eficiente la intersección en este caso.

In [69]:
term1 = stemmer.stem("early")
term2 = stemmer.stem("telecommunication")
p1 = inverted_index.get(term1, [])
p2 = inverted_index.get(term2, [])

print("early:", p1)
print("telecommunication:", p2)

print(term1)
print(term2)

print("early:", p1)
print("telecommunication:", p2)

early: ['d001', 'd003', 'd009', 'd014', 'd015', 'd016', 'd017', 'd018', 'd021', 'd022', 'd023', 'd024', 'd025', 'd027', 'd029', 'd034', 'd035', 'd039', 'd045', 'd046', 'd048', 'd052', 'd054', 'd055', 'd056', 'd057', 'd058', 'd060', 'd061', 'd063', 'd065', 'd066', 'd068', 'd069', 'd071', 'd073', 'd074', 'd076', 'd077', 'd080', 'd081', 'd085', 'd086', 'd091', 'd093', 'd095', 'd097', 'd100', 'd101', 'd107', 'd109', 'd110', 'd113', 'd115', 'd118', 'd122', 'd124', 'd126', 'd129', 'd130', 'd131', 'd132', 'd133', 'd135', 'd136', 'd137', 'd138', 'd141', 'd142', 'd144', 'd146', 'd148', 'd151', 'd152', 'd154', 'd159', 'd167', 'd168', 'd171', 'd172', 'd173', 'd174', 'd175', 'd185', 'd190', 'd192', 'd193', 'd194', 'd198', 'd199', 'd201', 'd203', 'd204', 'd205', 'd209', 'd211', 'd212', 'd214', 'd215', 'd216', 'd218', 'd219', 'd221', 'd223', 'd229', 'd230', 'd231', 'd232', 'd233', 'd234', 'd235', 'd237', 'd240', 'd241', 'd244', 'd247', 'd248', 'd249', 'd250', 'd251', 'd255', 'd257', 'd259', 'd262', 'd263', 'd264', 'd268', 'd271', 'd273', 'd279', 'd280', 'd281', 'd282', 'd283', 'd285', 'd289', 'd291', 'd293', 'd295', 'd299', 'd301', 'd303', 'd305', 'd307', 'd310', 'd312', 'd313', 'd316', 'd319', 'd320', 'd322', 'd323', 'd324', 'd325', 'd328', 'd329', 'd330', 'd331']
telecommunication: ['d060', 'd100', 'd231']
earli
telecommun
early: ['d001', 'd003', 'd009', 'd014', 'd015', 'd016', 'd017', 'd018', 'd021', 'd022', 'd023', 'd024', 'd025', 'd027', 'd029', 'd034', 'd035', 'd039', 'd045', 'd046', 'd048', 'd052', 'd054', 'd055', 'd056', 'd057', 'd058', 'd060', 'd061', 'd063', 'd065', 'd066', 'd068', 'd069', 'd071', 'd073', 'd074', 'd076', 'd077', 'd080', 'd081', 'd085', 'd086', 'd091', 'd093', 'd095', 'd097', 'd100', 'd101', 'd107', 'd109', 'd110', 'd113', 'd115', 'd118', 'd122', 'd124', 'd126', 'd129', 'd130', 'd131', 'd132', 'd133', 'd135', 'd136', 'd137', 'd138', 'd141', 'd142', 'd144', 'd146', 'd148', 'd151', 'd152', 'd154', 'd159', 'd167', 'd168', 'd171', 'd172', 'd173', 'd174', 'd175', 'd185', 'd190', 'd192', 'd193', 'd194', 'd198', 'd199', 'd201', 'd203', 'd204', 'd205', 'd209', 'd211', 'd212', 'd214', 'd215', 'd216', 'd218', 'd219', 'd221', 'd223', 'd229', 'd230', 'd231', 'd232', 'd233', 'd234', 'd235', 'd237', 'd240', 'd241', 'd244', 'd247', 'd248', 'd249', 'd250', 'd251', 'd255', 'd257', 'd259', 'd262', 'd263', 'd264', 'd268', 'd271', 'd273', 'd279', 'd280', 'd281', 'd282', 'd283', 'd285', 'd289', 'd291', 'd293', 'd295', 'd299', 'd301', 'd303', 'd305', 'd307', 'd310', 'd312', 'd313', 'd316', 'd319', 'd320', 'd322', 'd323', 'd324', 'd325', 'd328', 'd329', 'd330', 'd331']
telecommunication: ['d060', 'd100', 'd231']

In [75]:
resultado_sin, comparaciones_sin = intersect_without_skips(
    p1,
    p2
)

skips_p1 = build_skip_pointers(p1)
skips_p2 = build_skip_pointers(p2)

resultado_con, comparaciones_con, skips_utilizados = intersect_with_skips(
    p1,
    p2,
    skips_p1,
    skips_p2
)

print("Resultado sin skips:", resultado_sin)
print("Resultado con skips:", resultado_con)

print("Comparaciones sin skips:", comparaciones_sin)
print("Comparaciones con skips:", comparaciones_con)

print("Skip pointers utilizados:", skips_utilizados)

print("Reducción al usar skips:", ((107 - 41) / 107) * 100, "%")

Resultado sin skips: ['d060', 'd100', 'd231']
Resultado con skips: ['d060', 'd100', 'd231']
Comparaciones sin skips: 107
Comparaciones con skips: 41
Skip pointers utilizados: 6
Reducción al usar skips: 61.6822429906542 %

#### Consultas binarias AND

In [28]:
queries_path = Path("queries-raw-texts")
query_files = list(queries_path.glob("*.naf"))

queries = []

for file_path in query_files:
    query = read_naf_document(file_path)
    queries.append(query)

In [29]:
queries[:5]

[{'id': 'q01', 'contenido': 'Fabrication of music instruments'},
 {'id': 'q02', 'contenido': 'famous German poetry'},
 {'id': 'q03', 'contenido': 'Romanticism'},
 {'id': 'q04', 'contenido': 'University of Edinburgh research'},
 {'id': 'q06', 'contenido': 'bridge construction'}]

In [30]:
for query in queries:

    content = clean_text(query["contenido"])
    contentN = normalize_text( content,True)
    tokens = [
        token.text
        for token in nlp(contentN)
        if not token.is_punct and not token.is_stop
    ]
    query["stems"] = [ stemmer.stem(token) for token in tokens]

In [31]:
resultados_queries = []

for query in queries:

    terms = query["stems"]

    if not terms:
        resultados_queries.append({
            "query": query["id"],
            "terminos": "",
            "resultado": [],
            "comparaciones_sin_skips": 0,
            "comparaciones_con_skips": 0,
            "skips_utilizados": 0,
            "iguales": True
        })
        continue

    resultado_sin = inverted_index.get(terms[0], [])
    comparaciones_sin = 0

    for term in terms[1:]:
        postings = inverted_index.get(term, [])
        resultado_sin, comparaciones = intersect_without_skips(
            resultado_sin,
            postings
        )
        comparaciones_sin += comparaciones

        if not resultado_sin:
            break

    resultado_con = inverted_index.get(terms[0], [])
    comparaciones_con = 0
    skips_utilizados = 0

    for term in terms[1:]:

        postings = inverted_index.get(term, [])

        skips_resultado = build_skip_pointers(resultado_con)
        skips_postings = build_skip_pointers(postings)

        resultado_con, comparaciones, skips = intersect_with_skips(
            resultado_con,
            postings,
            skips_resultado,
            skips_postings
        )

        comparaciones_con += comparaciones
        skips_utilizados += skips

        if not resultado_con:
            break

    resultados_queries.append({
        "query": query["id"],
        "terminos": " AND ".join(terms),
        "resultado": resultado_con,
        "comparaciones_sin_skips": comparaciones_sin,
        "comparaciones_con_skips": comparaciones_con,
        "skips_utilizados": skips_utilizados,
        "iguales": resultado_sin == resultado_con
    })

tabla_queries = pd.DataFrame(resultados_queries)

display(tabla_queries)

,query,terminos,resultado,comparaciones_sin_skips,comparaciones_con_skips,skips_utilizados,iguales
0,q01,fabric AND music AND instrument,[],34,26,2,True
1,q02,famou AND german AND poetri,"[d291, d293]",257,245,2,True
2,q03,romantic,"[d105, d147, d152, d283, d291, d318]",0,0,0,True
3,q04,univers AND edinburgh AND research,[d286],324,170,14,True
4,q06,bridg AND construct,"[d026, d029, d069, d257, d297, d303, d329]",68,56,2,True
5,q07,walk AND fame AND star,"[d004, d034]",32,32,0,True
6,q08,scientist AND work AND atom AND bomb,"[d108, d110, d117, d205, d251]",411,403,1,True
7,q09,invent AND internet,"[d198, d205, d223]",53,25,4,True
8,q10,earli AND telecommun AND method,[d231],158,64,10,True
9,q12,explor AND south AND pole,"[d176, d250, d277]",69,65,2,True
10,q13,famou AND member AND royal AND navi,[],299,288,3,True
11,q14,nobel AND prize AND win AND invent,[],118,99,4,True
12,q16,south AND america,"[d132, d150, d176, d184, d229, d250, d277]",46,46,0,True
13,q17,edward AND teller AND mari AND curi,"[d121, d271]",36,21,5,True
14,q18,comput AND languag AND program AND artifici AN...,"[d192, d194, d203, d210]",142,138,2,True
15,q19,william AND hearst AND movi,[d179],31,10,4,True
16,q22,captain AND jame AND cook AND explor,[],49,44,2,True
17,q23,grace AND hopper AND famou,[d219],120,32,8,True
18,q24,comput AND astronomi,"[d129, d221, d240, d282]",86,68,3,True
19,q25,wwii AND aircraft,[],0,0,0,True
20,q26,literari AND critic AND thoma AND moor,[],108,94,4,True
21,q27,nazi AND confisc AND destroy AND art AND liter...,[],23,23,0,True
22,q28,modern AND age AND english AND literatur,"[d136, d174]",310,300,3,True
23,q29,modern AND physiolog,"[d037, d046, d294]",78,64,2,True
24,q32,roman AND empir,"[d025, d031, d090, d139, d254]",36,36,0,True
25,q34,scientist AND contribut AND photosynthesi,[],170,170,0,True
26,q36,aviat AND pioneer AND public,"[d257, d265]",164,84,11,True
27,q37,gutenberg AND bibl,[d169],7,7,0,True
28,q38,religi AND belief AND scientist AND explor,[],182,97,10,True
29,q40,carl AND friedrich AND gauss AND influenc AND ...,[],139,95,8,True
30,q41,person AND hannov,"[d150, d174]",63,28,5,True
31,q42,skinner AND experi AND oper AND condit AND cha...,[],170,33,22,True
32,q44,napoleon AND russian AND campaign,"[d029, d185]",40,38,1,True
33,q45,friend AND enemi AND napoleon AND bonapart,[d105],76,55,4,True
34,q46,woman AND won AND nobel AND prize,[],75,67,2,True

In [32]:
tabla_queries_ordenada = tabla_queries.copy()
numeros = []

for query_id in tabla_queries_ordenada["query"]:
    numeros.append(int(query_id[1:]))

tabla_queries_ordenada["numero_query"] = numeros
tabla_queries_ordenada = tabla_queries_ordenada.sort_values("numero_query")
output_path = Path("BSII-AND-queries_results")

with output_path.open("w", encoding="utf-8") as output_file:
    for _, row in tabla_queries_ordenada.iterrows():
        documents_found = sorted(row["resultado"])
        output_file.write(
            f'{row["query"]} {",".join(documents_found)}\n'
        )

print(f"Archivo generado: {output_path.resolve()}")

Archivo generado: C:\Users\adwar\Documents\repositorios\Learning\NLP-ml\Tarea1\BSII-AND-queries_results

## Recuperación ranqueada y vectorización de documentos (RRDV)

### Representación vectorial ponderada tf.idf

La estrategia utiliza el índice invertido para obtener el DF de cada término y limitar el cálculo del TF a los documentos en los que el término aparece. Esto evita calcular el TF para documentos en los que el término no está presente y aprovecha la estructura construida para BSII. Sin embargo, el índice invertido almacena únicamente los identificadores de los documentos, por lo que la frecuencia del término debe calcularse nuevamente a partir de los tokens de cada documento. Además, para localizar cada documento asociado a un posting, la implementación recorre la colección de documentos. Por esta razón, aunque se reduce el número de documentos sobre los que se calcula el TF, la implementación no es completamente eficiente

In [33]:
def build_tfidf_matrix(inverted_index, documents):
    """Construye la matriz TF-IDF utilizando el índice invertido para obtener
    el DF y calcular el peso de cada término en los documentos donde aparece.
    
    Parameters:
        inverted_index: Diccionario del Índice invertido en donde relaciona cada término con la lista de identificadores de los documentos en los que aparece.
        documents: Lista de documentos que contiene sus identificadores y tokens, utilizados para calcular la frecuencia del término (TF).
    Returns:
        tf_idf_matriz: Matriz TF-IDF representada como un diccionario donde cada término contiene los documentos en los que aparece y su respectivo peso TF-IDF.
    """
    tf_idf_matrix = {}

    for term in inverted_index:
        tf_idf_matrix[term] = {}
        df = len(inverted_index[term])
        idf = np.log10(len(documents) / df)

        for document_id in inverted_index[term]:
            for document in documents:
                if document["id"] == document_id:
                    tf = document["tokens"].count(term)
                    tf_idf_matrix[term][document_id] = np.log10(1 + tf) * idf
                    break

    return tf_idf_matrix     

 
tf_idf_matrix = build_tfidf_matrix(inverted_index, documents)

In [34]:
def build_document_vectors(tf_idf_matrix, documents):
    """
    Construye un vector TF-IDF para cada documento a partir de la matriz TF-IDF, asignando cero a los términos que no aparecen en el documento.

    Parameters:
        tf_idf_matrix: Diccionario de la Matriz TF-IDF representada como un diccionario
            de términos, documentos y sus respectivos pesos.
        documents: Lista de documentos con sus identificadores.

    Returns:
        dict: Diccionario que relaciona cada identificador de documento con su vector TF-IDF.
    """
    document_vectors = {}

    for document in documents:
        document_id = document["id"]
        vector = []
        for term in tf_idf_matrix:
            vector.append(tf_idf_matrix[term].get(document_id, 0))
        document_vectors[document_id] = vector

    return document_vectors

document_vectors = build_document_vectors(tf_idf_matrix,documents)

def build_query_vector(query, tf_idf_matrix, inverted_index, documents):
    """Construye el vector TF-IDF de una consulta utilizando el mismo
    vocabulario y esquema de ponderación empleado para los documentos.

    Parameters:
        query: Diccionario de la consulta procesada que contiene los términos normalizados o stemmizados.
        tf_idf_matrix: Diccionario Matriz TF-IDF utilizada para definir el vocabulario y los pesos de los términos.
        inverted_index: Diccionario Índice invertido utilizado para obtener el DF de cada término de la consulta.
        documents : Lista de documentos utilizada para calcular el IDF.

    Returns:
        list: Vector TF-IDF correspondiente a la consulta."""
    
    query_vector = []
    for term in tf_idf_matrix:
        tf = query["stems"].count(term)
        if tf > 0:
            df = len(inverted_index[term])
            idf = np.log10(len(documents) / df)
            tf_idf = np.log10(1 + tf) * idf
        else:
            tf_idf = 0
        query_vector.append(tf_idf)
    return query_vector
    

# vector ara uno de los queries
query_vector = build_query_vector(
    query,
    tf_idf_matrix,
    inverted_index,
    documents
)
print("Dimensión:", len(query_vector))
print("Primeros 10 valores:", query_vector[:10])

Dimensión: 13923
Primeros 10 valores: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [35]:

ids = list(document_vectors.keys())[:10]

# Terminos que tienen algun peso en esos documentos
terms = []

for term in tf_idf_matrix:
    if any(tf_idf_matrix[term].get(doc_id, 0) > 0 for doc_id in ids):
        terms.append(term)

# Construimos la tabla
vector_table = pd.DataFrame(
    {
        term: [tf_idf_matrix[term].get(doc_id, 0) for doc_id in ids]
        for term in terms
    },
    index=ids
)

vector_table = vector_table.T
display(vector_table)

,d001,d002,d003,d004,d005,d006,d007,d008,d009,d010
william,0.638752,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.247103,0.000000
beaumont,2.806946,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.000000
human,0.353870,0.223267,0.0,0.0,0.0,0.0,0.223267,0.0,0.000000,0.000000
digest,1.879585,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.000000
physiolog,1.006969,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...
protein,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.614916
dynam,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.504144
soul,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.486687
implic,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.548133
bodi,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.266821

### Similitud del coseno

In [36]:
def cosine_similarity(vector1, vector2):
    """Calcula la similitud coseno entre dos vectores y retorna un valor que representa su similitud.
    
    Parameters:
        vector1: Lista primer vector numérico.
        vector2: Lista segundo vector numérico.

    Returns:
        float: Similitud coseno entre los dos vectores. Retorna 0 si
            alguno de los vectores tiene norma cero."""
    dot_product = np.dot(vector1, vector2)
    norm1 = np.linalg.norm(vector1)
    norm2 = np.linalg.norm(vector2)

    if norm1 == 0 or norm2 == 0:
        return 0

    return dot_product / (norm1 * norm2)

d1 = document_vectors["d096"]
d2 = document_vectors["d169"]

similarity = cosine_similarity(d1, d2)

print("Similitud:", similarity)

Similitud: 0.01940197047531942

In [37]:
def rank_documents(query,document_vectors,tf_idf_matrix,inverted_index,documents):
    """
    Ordena los documentos según su similitud coseno con una consulta, colocando primero los documentos con mayor similitud.

    Parameters:
        query (dict): Consulta procesada que contiene sus términos.
        document_vectors (dict): Vectores TF-IDF de los documentos.
        tf_idf_matrix (dict): Matriz TF-IDF utilizada para construir el vector de la consulta.
        inverted_index (dict): Índice invertido utilizado para obtener el DF de los términos.
        documents (list): Lista de documentos utilizada para calcular el IDF.

    Returns:
        list: Lista de tuplas con el identificador del documento y su
            similitud con la consulta, ordenada de mayor a menor similitud.
    """
    query_vector = build_query_vector(query,tf_idf_matrix,inverted_index,documents)
    rankings = []

    for document_id, document_vector in document_vectors.items():

        similarity = cosine_similarity(query_vector,document_vector)

        if similarity > 0:
            rankings.append((document_id, similarity))

    return sorted(rankings,key=lambda x: x[1],reverse=True)

In [38]:
coseno_rankings = {}

for query in queries:
    coseno_rankings[query["id"]] = rank_documents(query,document_vectors,tf_idf_matrix,inverted_index,documents)

In [39]:
filas = []

for query_id, ranking in coseno_rankings.items():

    for posicion, (document_id, similarity) in enumerate(ranking[:10], start=1):

        filas.append({
            "query": query_id,
            "posición": posicion,
            "documento": document_id,
            "similitud": similarity
        })

tabla_ranking = pd.DataFrame(filas)

display(tabla_ranking)

    query  posición documento  similitud
0     q01         1      d259   0.109798
1     q01         2      d085   0.087924
2     q01         3      d186   0.075858
3     q01         4      d254   0.072904
4     q01         5      d016   0.071303
..    ...       ...       ...        ...
341   q46         6      d091   0.081280
342   q46         7      d081   0.081024
343   q46         8      d121   0.077181
344   q46         9      d013   0.076337
345   q46        10      d005   0.075722

[346 rows x 4 columns]

In [40]:
query_id = "q06"

tabla_q06 = pd.DataFrame(
    coseno_rankings[query_id][:10],
    columns=["documento", "similitud"]
)

tabla_q06.insert(0, "posición", range(1, len(tabla_q06) + 1))

display(tabla_q06)

   posición documento  similitud
0         1      d329   0.230026
1         2      d297   0.224940
2         3      d026   0.160921
3         4      d029   0.120839
4         5      d233   0.106594
5         6      d025   0.104681
6         7      d257   0.103213
7         8      d069   0.065687
8         9      d186   0.045624
9        10      d077   0.043958

In [41]:
ids = ["d329", "d297", "d026","d029","d233"]

for document in documents:
    if document["id"] in ids:
        print("=" * 80)
        print("ID:", document["id"])
        print("Título:", document["titulo"])
        print("Contenido:", document["contenido_limpio"])

================================================================================
ID: d026
Título: Jean-Rondolphe Perronet and the Bridges of Paris
Contenido: jean-rondolphe perronet and the bridges of paris jean-rodolphe perronet (1708-1794). on october 27, 1708, french architect and structural engineer jean-rodolphe perronet was born. he is best known for his many stone arch bridges, among them his most popular work, the paris pont de la concorde. jean-rodolphe perronet was born in suresnes, a suburb of paris, the son of a swiss guardsman. at 17 he entered the architectural practice of jean beausire, “first architect” to the city of paris, as an apprentice. he was put in charge of the design and construction of paris’s grand sewer, embankment works and the maintenance of the banlieue’s roads. in 1735, he was named sous-ingenieur (under-engineer) to alencon. perronet’s perceived energy for the district of alencon came to the notice of trudaine – the overseer of finances in charge of roads – who put him in charge of training surveyors and those drawing maps to provide competent staff for the ponts et chaussees - bridges and embankments (civil engineering department) in 1736. [3] in 1737, he became sous-ingenieur, then engineer to the generalite of alencon. in 1747, perronet was named director of the bureau des dessinateurs du roi (royal office of designers), which had also just put daniel-charles trudaine in charge of producing maps and plans for the kingdom. this first ecole des ponts et chaussees was based in the hotel liberal bruant in paris. perronet was given the task of training bridge and road engineers and of overseeing their work in the generalites in which they worked. the bureau became the bureau des eleves des ponts et chaussees, then in 1775 was renamed the ecole des ponts et chaussees. its organiser, inspiration and teacher, perronet was a true spiritual father to his students and used a new teaching method which seems very contemporary to modern eyes. during this time he became friends with the swiss bridge-builder charles labelye. perronet was an outstanding leader and teacher, and the “spiritual father” of the 350 engineers he trained during the 47 years in which he directed the school. once they had qualified from the school, perronet was often responsible for their appointments and then followed their progress and gave them advice throughout their careers. perronet’s work as an engineer is just as remarkable and innovative as his work as an administrator. during construction of a bridge at mantes in 1763, perronet made the discovery that the horizontal thrust of a series of elliptical arches was passed along to the abutments at the ends of the bridge. armed with this knowledge, he carried the stone arch bridge to its ultimate design form, with extremely flat arches that were supported during construction by timbering (falsework) and mounted on very slender piers, which widened the waterway for navigation and reduced scour from the current.[2] pont de neuilly, completed in 1794 besides his 13 bridges, he constructed more than 2500 km of tree-lined roads when working for the district of paris, but also worked as a hydraulic engineer on the canal de l’yvette [3] the best-known bridges — among the thirteen that perronet designed — are the pont de neuilly (completed 1774 and often called the most graceful stone bridge ever built), the pont sainte-maxence (1785), and the pont de la concorde (1791), still standing. perroner was named premier ingenieur du roi in 1763 and became a member of the associate of the academie des sciences in 1765. besides his bridges, he also contributed the article pompe a feu (fire-engine) to the encyclopedie ou dictionnaire raisonne des sciences, des arts et des metiers. in 1772, perronet was elected a foreign member of the royal swedish academy of sciences. he was 80 years old when he began the pont de la concorde, originally called the pont louis xv, in 1787. despite the outbreak of the french revolution, he kept the work going, completing it in 1791. in 1794, perronet died in paris, aged 85. at yovisto, unfortunately we don’t have a video featuring the work of jean-rodolphe perronet. nevertheless, you might be interested in a lecture of design thinking by timothy brown about ‘designers should think big‘.
================================================================================
ID: d029
Título: Charles Joseph Minard and the Art of Infographics
Contenido: charles joseph minard and the art of infographics charles joseph minard (1781-1870). on october 24, 1870, french civil engineer charles joseph minard passed away. he is best noted for his ground breaking inventions in the field of information graphics. charles joseph minard was born on march 27, 1781, in dijon, france, as the son of pierre etienne minard, a clerk of the court and an officer of the secondary school, and benign lame lady. he was baptized at saint michel on the day of his birth. at age four minard learned to read and to write, and when he was six his father enrolled him an elementary course in anatomy. he completed his fourth year of study at the secondary school at dijon early, and then applied himself to studying latin, literature, and physical and math sciences. at age 15, he was admitted to the prestigious ecole polytechnique, where among his professors among others lagrange and fourier made a profound impression on him [1]. he left there in order to study civil engineering at ecole nationale des ponts et chaussees (the school of bridges and roads). in september 1810 he was sent by the government to anvers and then almost immediately to the port of flessingue. there, he solved a critical problem with a cofferdam that was leaking water faster than it could be removed. he solved the problem by using pumps driven by a steam engine, only the third time this solution had been applied to a project. he worked for many years as a civil engineer on the construction of dams, canals and bridge projects throughout europe. on november 1, 1830, he was named superintendent of the school of bridges and roads, where he continued to serve through 1836. while there he was awarded the cross of the legion of honor. he then became inspector of the corps of bridges until he retired in 1851, after which he dedicated himself to private research. charles minard’s map of napoleon’s disastrous russian campaign of 1812. minard was a pioneer of the use of graphics in engineering and statistics. he first began to publish cartes figuratives (figurative maps) during the mid-1840s, when he was nearly sixty-five years old. most of his early maps dealt with flows of goods and passengers along railroad, river and oceangoing routes of commerce. minard’s maps became renowned around france not so much for their statistical or cartographic merits, but for the style he used in visualizing the numerical and relational aspects of flows.[2] he is most well known for his famous cartographic depiction of numerical data on a map of of napoleon’s disastrous losses suffered during the russian campaign of 1812 (carte figurative des pertes successives en hommes de l’armee francaise dans la campagne de russie 1812-1813). the illustration is perhaps the single best-known statistical graphic of the nineteenth century and depicts napoleon’s army departing the polish-russian border. a thick band illustrates the size of his army at specific geographic points during their advance and retreat. it displays six types of data in two dimensions: the number of napoleon’s troops[2,3] this type of band graph for illustration of flows was later named sankey diagram. at yovisto you can learn more about the visualization of statistical data in the famous ted-talk of prof. hans rosling on ‘let my dataset change your mindset‘.
================================================================================
ID: d233
Título: The Steel of Sir Henry Bessemer
Contenido: the steel of sir henry bessemer sir henry bessemer (1813 – 1898) . on january 19, 1813, english engineer, inventor, and businessman sir henry bessemer was born. bessemer’s name is chiefly known in connection with the bessemer process, the first process for manufacturing steel inexpensively (1856), leading to the development of the bessemer converter. henry bessemer was born on january 19, 1813 in charlton, hertfordshire, england. he was the son of an engineer and typefounder and he showed a great interest in making own inventions at early age. bessemer proved to be mechanically skilled and had his first success selling ‘gold’ powder made from brass as a paint additive. henry bessemer also patented a method for making a continuous ribbon of plate glass in 1848, but it was not really commercially successful. through the years, henry bessemer thought of more and more inventions and he began working on the problem of manufacturing cheap steel for ordnance production from 1850 to 1855 when he patented his method. he first described the process to a meeting of the british association in cheltenham which he titled “the manufacture of iron without fuel.” the famous bessemer process involved the procedure of oxygen blown in the air through molten pig iron to burn off the impurities and thus create steel. it is known that james nasmyth had been working on a similar idea for some time prior to this. however, after hearing bessemer talk about his invention, nasmyth turned his project down as he was about to retire anyway. the general lack of steel was hard for all industries back then and they had to rely on cast iron as well as wrought iron. there were several accidents when cast iron beams collapsed suddenly, such as the dee bridge disaster of may 1847, the wooton bridge collapse and the bull bridge accident of 1860. the failures continued until all cast iron under-bridges were replaced by steel structures. as the cost of production steel decreased, the material was starting to be widely substituted for cast iron. when bessemer licensed the patent for his process to several ironmasters, the companies had great difficulties producing steel of an acceptable quality. the swedish ironmaster goran fredrik then tried using purer charcoal pig iron and made good steel by the process after numerous attempts. also, it had been shown that the quantity of carbon could be controlled by removing almost all of it from the iron and then adding an exact amount of carbon and manganese. the process highly improved the quality of the material and was first introduced by robert forester mushet. the inventor and businessman erected steelworks in sheffield in a business partnership with others and began to manufacture steel. when mushet’s daughter, mary, decided to travel to london in order to confront bessemer at his offices, arguing that his success was based on the results of her father’s work. bessemer decided to pay mushet an annual pension of £300, a very considerable sum, which he is assumed to have paid for over 20 years, possibly with the purpose to keeping the mushets from legal action. at yovisto you may learn more about the topic in the video lecture ‘from the european coal and steel community to the common market’ by prof. dr. vernon bogdanor at gresham college.
================================================================================
ID: d297
Título: The Sydney Harbour Bridge
Contenido: the sydney harbour bridge sydney harbour shot taken from the air. bridge with the opera house to the side image: rodney haywood. on march 19, 1932, the sydney harbour bridge was opened, which connects the sydney central business district and the north shore. it is the sixth longest spanning-arch bridge in the world, and it is the tallest steel arch bridge, measuring 134 m from top to water level. the first proposals to building a bridge from the northern to the southern shore of the harbour were made in 1815 by francis greenway. he wrote a letter to the then “the australian” newspaper stating that such a bridge would “give an idea of strength and magnificence that would reflect credit and glory on the colony and the mother country” ten years later. however, nothing happened. several years later, in 1840 naval architect robert brindley proposed that a floating bridge be built. only in 1900 the government organised a worldwide competition for the design and construction of a harbour bridge and the first submissions arrived. unfortunately, all submissions were considered unsuitable and so the momentum for the bridge crossing stopped. after world war i, the plans got more serious. the new south wales government then invited worldwide tenders for the construction of the bridge in 1922 and the contract was given to the english firm dorman long and co of middlesbrough. the construction work began in 1924 and took 1.400 men eight years to build. on this day, the bridge carries eight traffic lanes and two rail lines. for the opening of the bridge on march 19, 1932, john ‘jack’ t. lang was chosen to cut the ribbon to signify the opening of the harbour bridge. then, captain francis de groot of the political group the new guard slashed the ribbon with his sword. captain de goot believed that the only person to open the bridge should be a member of the royal family. captain de goot was detained, the ribbon tied together, and the premier then officially cut the ribbon. it has been reported that in the 1940s, many pilots flew under the bridge with their planes including the flight lieutenant peter isaacson during tour around australia to raise funds for the war effort. the famous bridge climb started in 1998. it attracts tourists as well as locals as the view is supposed to be breathtaking. several celebrities are reported to have climbed sydney’s harbour bridge including prince frederik and princess mary of denmark, matt damon, hugo weaving, sarah ferguson, cathy freeman, kylie minogue and kostya tszyu. at yovisto, you may learn more about lessons in bridge engineering in a lecture by john stanton. references and futher reading: sydney harbour bridge website sydney harbour bridge at structurae
================================================================================
ID: d329
Título: Squire Whipple – The Father of the Iron Bridge
Contenido: squire whipple – the father of the iron bridge truss bridge patented by squire whipple. on september 16, 1804, us-american civil engineer squire whipple was born. he who provided the first scientifically based rules for bridge construction and has become known as the father of iron bridge building in america. the civil engineer was born in hardwick, massachusetts in 1804 the son of a farmer. he was exposed to construction sites and materials from early age, since his father designed, built and ran a cotton-spinning mill in nearby greenwich, massachusetts. after receiving the best common school education available he attended hartwick academy and fairfield academy located in central new york near his home. in 1830 whipple graduated from union college in schenectady, new york after one year of study. he spent the decade of the 1830s serving his apprenticeship working on the baltimore and ohio railroad, the erie canal enlargement, the new york and erie railroad and several other railroads. when work was slow, he designed, built and sold mathematical instruments such as transits and engineer’s levels and drafting equipment. [1] in the early 1840s, whipple designed and built a weigh lock scale with a capacity of 300 tons to weigh the canal boats on the enlarged erie canal in utica. this was probably the largest weighing device in the country at the time. after a while, whipple became interested in the design and construction of iron and wooden bridges. having worked on the enlargement of the erie canal, he knew that wooden bridges that crossed the original canal had a short-life. he also knew that the new, wider canal would require longer span bridges and must be made of a modern material, iron.[1,3] his very first bowstring iron truss was patented in 1841. his patent showed an understanding of structural behavior of the diagonals and verticals and the need to size them to handle their loads as either tension or compression members. the engineer received his first chance to build a bridge across the canal at first street in utica fell. he tried to convince the canal commissioners that a bridge built of iron was a good long-term investment, but they were reluctant to trust a new material for their bridge. to illustrate the stability and strength of his bridge, whipple had one built at his own expense on a vacant lot in utica near the offices of the canal commissioners. when the first street bridge fell, they approved the construction of his bridge.[1,2] at yovisto, you may be interested in a video of the golden gate bridge opening in 1937.

### BM25

In [42]:
corpus = [document["tokens"] for document in documents]

bm25 = BM25Okapi(
    corpus,
    k1=1.5,
    b=0.75
)
bm25_rankings = {}
filas = []
for query in queries:
    scores = bm25.get_scores(query["stems"])
    bm25_rankings[query["id"]] = [(documents[i]["id"], scores[i]) for i in np.argsort(scores)[::-1] if scores[i] > 0]

for query_id, ranking in bm25_rankings.items():

    for posicion, (document_id, score) in enumerate(ranking[:10], start=1):

        filas.append({
            "query": query_id,
            "posición": posicion,
            "documento": document_id,
            "BM25": score
        })

tabla_bm25 = pd.DataFrame(filas)

display(tabla_bm25)

    query  posición documento      BM25
0     q01         1      d085  8.132767
1     q01         2      d254  7.971316
2     q01         3      d186  7.405890
3     q01         4      d016  7.022649
4     q01         5      d259  6.726422
..    ...       ...       ...       ...
341   q46         6      d145  8.482019
342   q46         7      d117  8.258585
343   q46         8      d247  8.187469
344   q46         9      d094  8.172796
345   q46        10      d121  7.674628

[346 rows x 4 columns]

Al variar b entre 0 y 1 se observa que la normalización por longitud afecta el ranking de BM25. Para q06, con b=0, d297 ocupa el primer lugar y d329 el segundo; al aumentar b hasta 0.50, sus posiciones se intercambian y d329 permanece primero hasta b=1. Otros documentos, como d026, mantienen su posición durante toda la variación. Esto muestra que el efecto de b depende de las características de cada documento y que una mayor normalización por longitud puede modificar el orden de documentos con puntajes similares.

In [43]:
"Prueba de variacion de b "
query = next(q for q in queries if q["id"] == "q06")

resultados_bm25 = []

for b in [0, 0.25, 0.5, 0.75, 1]:

    bm25 = BM25Okapi(
        corpus,
        k1=1.5,
        b=b
    )

    scores = bm25.get_scores(query["stems"])
    ranking = [(documents[i]["id"], scores[i])for i in np.argsort(scores)[::-1] if scores[i] > 0]

    for posicion, (documento, score) in enumerate(ranking[:10], 1):

        resultados_bm25.append({
            "b": b,
            "posición": posicion,
            "documento": documento,
            "score": score
        })

In [44]:
tabla_bm25 = pd.DataFrame(resultados_bm25)

tabla_bm25["resultado"] = (
    tabla_bm25["documento"] 
    + " (" 
    + tabla_bm25["score"].round(2).astype(str) 
    + ")"
)

tabla_bm25 = tabla_bm25.pivot(
    index="posición",
    columns="b",
    values="resultado"
)

display(tabla_bm25)

b                0.00         0.25         0.50         0.75         1.00
posición
1         d297 (9.54)  d297 (9.62)  d329 (9.72)  d329 (9.83)  d329 (9.96)
2         d329 (9.49)   d329 (9.6)  d297 (9.71)   d297 (9.8)  d297 (9.89)
3         d026 (9.43)  d026 (9.38)  d026 (9.34)  d026 (9.29)  d026 (9.24)
4         d257 (7.63)   d257 (7.5)  d257 (7.38)  d257 (7.26)   d029 (7.3)
5         d029 (6.99)  d029 (7.06)  d029 (7.14)  d029 (7.22)  d257 (7.15)
6         d025 (6.03)  d025 (6.04)  d025 (6.04)  d025 (6.05)  d025 (6.05)
7         d233 (5.48)  d233 (5.54)  d233 (5.61)  d233 (5.67)  d233 (5.73)
8         d303 (4.52)  d069 (4.65)   d069 (4.8)  d069 (4.95)  d069 (5.12)
9         d069 (4.52)  d303 (4.15)  d303 (3.84)  d303 (3.57)  d004 (3.49)
10        d004 (3.02)  d004 (3.12)  d004 (3.24)  d004 (3.36)  d303 (3.34)

In [45]:
ids = ["d329", "d297", "d026","d029","d233"]

for document in documents:
    if document["id"] in ids:
        print("=" * 80)
        print("ID:", document["id"])
        print("Título:", document["titulo"])
        print("Contenido:", document["contenido_limpio"])

================================================================================
ID: d026
Título: Jean-Rondolphe Perronet and the Bridges of Paris
Contenido: jean-rondolphe perronet and the bridges of paris jean-rodolphe perronet (1708-1794). on october 27, 1708, french architect and structural engineer jean-rodolphe perronet was born. he is best known for his many stone arch bridges, among them his most popular work, the paris pont de la concorde. jean-rodolphe perronet was born in suresnes, a suburb of paris, the son of a swiss guardsman. at 17 he entered the architectural practice of jean beausire, “first architect” to the city of paris, as an apprentice. he was put in charge of the design and construction of paris’s grand sewer, embankment works and the maintenance of the banlieue’s roads. in 1735, he was named sous-ingenieur (under-engineer) to alencon. perronet’s perceived energy for the district of alencon came to the notice of trudaine – the overseer of finances in charge of roads – who put him in charge of training surveyors and those drawing maps to provide competent staff for the ponts et chaussees - bridges and embankments (civil engineering department) in 1736. [3] in 1737, he became sous-ingenieur, then engineer to the generalite of alencon. in 1747, perronet was named director of the bureau des dessinateurs du roi (royal office of designers), which had also just put daniel-charles trudaine in charge of producing maps and plans for the kingdom. this first ecole des ponts et chaussees was based in the hotel liberal bruant in paris. perronet was given the task of training bridge and road engineers and of overseeing their work in the generalites in which they worked. the bureau became the bureau des eleves des ponts et chaussees, then in 1775 was renamed the ecole des ponts et chaussees. its organiser, inspiration and teacher, perronet was a true spiritual father to his students and used a new teaching method which seems very contemporary to modern eyes. during this time he became friends with the swiss bridge-builder charles labelye. perronet was an outstanding leader and teacher, and the “spiritual father” of the 350 engineers he trained during the 47 years in which he directed the school. once they had qualified from the school, perronet was often responsible for their appointments and then followed their progress and gave them advice throughout their careers. perronet’s work as an engineer is just as remarkable and innovative as his work as an administrator. during construction of a bridge at mantes in 1763, perronet made the discovery that the horizontal thrust of a series of elliptical arches was passed along to the abutments at the ends of the bridge. armed with this knowledge, he carried the stone arch bridge to its ultimate design form, with extremely flat arches that were supported during construction by timbering (falsework) and mounted on very slender piers, which widened the waterway for navigation and reduced scour from the current.[2] pont de neuilly, completed in 1794 besides his 13 bridges, he constructed more than 2500 km of tree-lined roads when working for the district of paris, but also worked as a hydraulic engineer on the canal de l’yvette [3] the best-known bridges — among the thirteen that perronet designed — are the pont de neuilly (completed 1774 and often called the most graceful stone bridge ever built), the pont sainte-maxence (1785), and the pont de la concorde (1791), still standing. perroner was named premier ingenieur du roi in 1763 and became a member of the associate of the academie des sciences in 1765. besides his bridges, he also contributed the article pompe a feu (fire-engine) to the encyclopedie ou dictionnaire raisonne des sciences, des arts et des metiers. in 1772, perronet was elected a foreign member of the royal swedish academy of sciences. he was 80 years old when he began the pont de la concorde, originally called the pont louis xv, in 1787. despite the outbreak of the french revolution, he kept the work going, completing it in 1791. in 1794, perronet died in paris, aged 85. at yovisto, unfortunately we don’t have a video featuring the work of jean-rodolphe perronet. nevertheless, you might be interested in a lecture of design thinking by timothy brown about ‘designers should think big‘.
================================================================================
ID: d029
Título: Charles Joseph Minard and the Art of Infographics
Contenido: charles joseph minard and the art of infographics charles joseph minard (1781-1870). on october 24, 1870, french civil engineer charles joseph minard passed away. he is best noted for his ground breaking inventions in the field of information graphics. charles joseph minard was born on march 27, 1781, in dijon, france, as the son of pierre etienne minard, a clerk of the court and an officer of the secondary school, and benign lame lady. he was baptized at saint michel on the day of his birth. at age four minard learned to read and to write, and when he was six his father enrolled him an elementary course in anatomy. he completed his fourth year of study at the secondary school at dijon early, and then applied himself to studying latin, literature, and physical and math sciences. at age 15, he was admitted to the prestigious ecole polytechnique, where among his professors among others lagrange and fourier made a profound impression on him [1]. he left there in order to study civil engineering at ecole nationale des ponts et chaussees (the school of bridges and roads). in september 1810 he was sent by the government to anvers and then almost immediately to the port of flessingue. there, he solved a critical problem with a cofferdam that was leaking water faster than it could be removed. he solved the problem by using pumps driven by a steam engine, only the third time this solution had been applied to a project. he worked for many years as a civil engineer on the construction of dams, canals and bridge projects throughout europe. on november 1, 1830, he was named superintendent of the school of bridges and roads, where he continued to serve through 1836. while there he was awarded the cross of the legion of honor. he then became inspector of the corps of bridges until he retired in 1851, after which he dedicated himself to private research. charles minard’s map of napoleon’s disastrous russian campaign of 1812. minard was a pioneer of the use of graphics in engineering and statistics. he first began to publish cartes figuratives (figurative maps) during the mid-1840s, when he was nearly sixty-five years old. most of his early maps dealt with flows of goods and passengers along railroad, river and oceangoing routes of commerce. minard’s maps became renowned around france not so much for their statistical or cartographic merits, but for the style he used in visualizing the numerical and relational aspects of flows.[2] he is most well known for his famous cartographic depiction of numerical data on a map of of napoleon’s disastrous losses suffered during the russian campaign of 1812 (carte figurative des pertes successives en hommes de l’armee francaise dans la campagne de russie 1812-1813). the illustration is perhaps the single best-known statistical graphic of the nineteenth century and depicts napoleon’s army departing the polish-russian border. a thick band illustrates the size of his army at specific geographic points during their advance and retreat. it displays six types of data in two dimensions: the number of napoleon’s troops[2,3] this type of band graph for illustration of flows was later named sankey diagram. at yovisto you can learn more about the visualization of statistical data in the famous ted-talk of prof. hans rosling on ‘let my dataset change your mindset‘.
================================================================================
ID: d233
Título: The Steel of Sir Henry Bessemer
Contenido: the steel of sir henry bessemer sir henry bessemer (1813 – 1898) . on january 19, 1813, english engineer, inventor, and businessman sir henry bessemer was born. bessemer’s name is chiefly known in connection with the bessemer process, the first process for manufacturing steel inexpensively (1856), leading to the development of the bessemer converter. henry bessemer was born on january 19, 1813 in charlton, hertfordshire, england. he was the son of an engineer and typefounder and he showed a great interest in making own inventions at early age. bessemer proved to be mechanically skilled and had his first success selling ‘gold’ powder made from brass as a paint additive. henry bessemer also patented a method for making a continuous ribbon of plate glass in 1848, but it was not really commercially successful. through the years, henry bessemer thought of more and more inventions and he began working on the problem of manufacturing cheap steel for ordnance production from 1850 to 1855 when he patented his method. he first described the process to a meeting of the british association in cheltenham which he titled “the manufacture of iron without fuel.” the famous bessemer process involved the procedure of oxygen blown in the air through molten pig iron to burn off the impurities and thus create steel. it is known that james nasmyth had been working on a similar idea for some time prior to this. however, after hearing bessemer talk about his invention, nasmyth turned his project down as he was about to retire anyway. the general lack of steel was hard for all industries back then and they had to rely on cast iron as well as wrought iron. there were several accidents when cast iron beams collapsed suddenly, such as the dee bridge disaster of may 1847, the wooton bridge collapse and the bull bridge accident of 1860. the failures continued until all cast iron under-bridges were replaced by steel structures. as the cost of production steel decreased, the material was starting to be widely substituted for cast iron. when bessemer licensed the patent for his process to several ironmasters, the companies had great difficulties producing steel of an acceptable quality. the swedish ironmaster goran fredrik then tried using purer charcoal pig iron and made good steel by the process after numerous attempts. also, it had been shown that the quantity of carbon could be controlled by removing almost all of it from the iron and then adding an exact amount of carbon and manganese. the process highly improved the quality of the material and was first introduced by robert forester mushet. the inventor and businessman erected steelworks in sheffield in a business partnership with others and began to manufacture steel. when mushet’s daughter, mary, decided to travel to london in order to confront bessemer at his offices, arguing that his success was based on the results of her father’s work. bessemer decided to pay mushet an annual pension of £300, a very considerable sum, which he is assumed to have paid for over 20 years, possibly with the purpose to keeping the mushets from legal action. at yovisto you may learn more about the topic in the video lecture ‘from the european coal and steel community to the common market’ by prof. dr. vernon bogdanor at gresham college.
================================================================================
ID: d297
Título: The Sydney Harbour Bridge
Contenido: the sydney harbour bridge sydney harbour shot taken from the air. bridge with the opera house to the side image: rodney haywood. on march 19, 1932, the sydney harbour bridge was opened, which connects the sydney central business district and the north shore. it is the sixth longest spanning-arch bridge in the world, and it is the tallest steel arch bridge, measuring 134 m from top to water level. the first proposals to building a bridge from the northern to the southern shore of the harbour were made in 1815 by francis greenway. he wrote a letter to the then “the australian” newspaper stating that such a bridge would “give an idea of strength and magnificence that would reflect credit and glory on the colony and the mother country” ten years later. however, nothing happened. several years later, in 1840 naval architect robert brindley proposed that a floating bridge be built. only in 1900 the government organised a worldwide competition for the design and construction of a harbour bridge and the first submissions arrived. unfortunately, all submissions were considered unsuitable and so the momentum for the bridge crossing stopped. after world war i, the plans got more serious. the new south wales government then invited worldwide tenders for the construction of the bridge in 1922 and the contract was given to the english firm dorman long and co of middlesbrough. the construction work began in 1924 and took 1.400 men eight years to build. on this day, the bridge carries eight traffic lanes and two rail lines. for the opening of the bridge on march 19, 1932, john ‘jack’ t. lang was chosen to cut the ribbon to signify the opening of the harbour bridge. then, captain francis de groot of the political group the new guard slashed the ribbon with his sword. captain de goot believed that the only person to open the bridge should be a member of the royal family. captain de goot was detained, the ribbon tied together, and the premier then officially cut the ribbon. it has been reported that in the 1940s, many pilots flew under the bridge with their planes including the flight lieutenant peter isaacson during tour around australia to raise funds for the war effort. the famous bridge climb started in 1998. it attracts tourists as well as locals as the view is supposed to be breathtaking. several celebrities are reported to have climbed sydney’s harbour bridge including prince frederik and princess mary of denmark, matt damon, hugo weaving, sarah ferguson, cathy freeman, kylie minogue and kostya tszyu. at yovisto, you may learn more about lessons in bridge engineering in a lecture by john stanton. references and futher reading: sydney harbour bridge website sydney harbour bridge at structurae
================================================================================
ID: d329
Título: Squire Whipple – The Father of the Iron Bridge
Contenido: squire whipple – the father of the iron bridge truss bridge patented by squire whipple. on september 16, 1804, us-american civil engineer squire whipple was born. he who provided the first scientifically based rules for bridge construction and has become known as the father of iron bridge building in america. the civil engineer was born in hardwick, massachusetts in 1804 the son of a farmer. he was exposed to construction sites and materials from early age, since his father designed, built and ran a cotton-spinning mill in nearby greenwich, massachusetts. after receiving the best common school education available he attended hartwick academy and fairfield academy located in central new york near his home. in 1830 whipple graduated from union college in schenectady, new york after one year of study. he spent the decade of the 1830s serving his apprenticeship working on the baltimore and ohio railroad, the erie canal enlargement, the new york and erie railroad and several other railroads. when work was slow, he designed, built and sold mathematical instruments such as transits and engineer’s levels and drafting equipment. [1] in the early 1840s, whipple designed and built a weigh lock scale with a capacity of 300 tons to weigh the canal boats on the enlarged erie canal in utica. this was probably the largest weighing device in the country at the time. after a while, whipple became interested in the design and construction of iron and wooden bridges. having worked on the enlargement of the erie canal, he knew that wooden bridges that crossed the original canal had a short-life. he also knew that the new, wider canal would require longer span bridges and must be made of a modern material, iron.[1,3] his very first bowstring iron truss was patented in 1841. his patent showed an understanding of structural behavior of the diagonals and verticals and the need to size them to handle their loads as either tension or compression members. the engineer received his first chance to build a bridge across the canal at first street in utica fell. he tried to convince the canal commissioners that a bridge built of iron was a good long-term investment, but they were reluctant to trust a new material for their bridge. to illustrate the stability and strength of his bridge, whipple had one built at his own expense on a vacant lot in utica near the offices of the canal commissioners. when the first street bridge fell, they approved the construction of his bridge.[1,2] at yovisto, you may be interested in a video of the golden gate bridge opening in 1937.

### Creacion de archivos de resultados

In [46]:
with open("RRDV-consultas_resultados", "w", encoding="utf-8") as archivo:

    for query in queries:

        resultados = rank_documents(query,document_vectors,tf_idf_matrix, inverted_index,documents)

        resultados_formateados = [ f"{document_id}: {similitud:.6f}"  for document_id, similitud in resultados ]

        archivo.write(
            f"{query['id']} {','.join(resultados_formateados)}\n"
        )

In [47]:
with open("BM25-consultas_resultados", "w", encoding="utf-8") as archivo:

    for query_id, ranking in bm25_rankings.items():

        resultados = [f"{document_id}: {score:.6f}" for document_id, score in ranking]

        archivo.write(
            f"{query_id} {','.join(resultados)}\n"
        )

### Evaluacion de metricas (Resultados)

In [48]:
relevance_judgments = {}

with open("relevance-judgments.tsv", "r", encoding="utf-8") as archivo:
    for linea in archivo:
        query_id, documentos = linea.strip().split("\t")
        relevance_judgments[query_id] = {}
        for documento in documentos.split(","):
            document_id, relevancia = documento.split(":")
            relevance_judgments[query_id][document_id] = int(relevancia)

In [49]:
def evaluate_ranking(ranking, relevance_judgments):
    """
    Evalúa el ranking de documentos de cada consulta mediante P@M,
    R@M y NDCG@M, utilizando los juicios de relevancia correspondientes.

    Parameters:
        ranking (dict): Ranking de documentos por consulta con sus scores.
        relevance_judgments (dict): Juicios de relevancia por consulta.

    Returns:
        pd.DataFrame: Resultados de evaluación por consulta.
    """

    resultados = []

    for query_id, ranking_query in ranking.items():

        juicios = relevance_judgments.get(query_id, {})
        M = len(juicios)

        documentos = [document_id for document_id, score in ranking_query]

        relevancia_binaria = [ 1 if document_id in juicios else 0 for document_id in documentos]

        relevancia_graduada = [juicios.get(document_id, 0) for document_id in documentos]

        resultados.append({
            "query": query_id,
            "M": M,
            "P@M": metricas.precision_at_k(relevancia_binaria, M),
            "R@M": metricas.recall_at_k(relevancia_binaria, M, M),
            "NDCG@M": metricas.ndcg_at_k(
                relevancia_graduada, M, "linear"
            )
        })

    return pd.DataFrame(resultados)

#### BM25

In [50]:
resultados_bm25 = evaluate_ranking(
    bm25_rankings,
    relevance_judgments
)

display(resultados_bm25)

   query   M       P@M       R@M    NDCG@M
0    q01   3  0.666667  0.666667  0.507615
1    q02  11  0.545455  0.545455  0.584844
2    q03   6  1.000000  1.000000  0.989525
3    q04   7  0.857143  0.857143  0.890951
4    q06   6  0.666667  0.666667  0.826491
5    q07   4  0.250000  0.250000  0.509097
6    q08  12  0.750000  0.750000  0.886503
7    q09   6  1.000000  1.000000  0.917885
8    q10   8  0.375000  0.375000  0.477187
9    q12   4  0.750000  0.750000  0.775845
10   q13   5  0.800000  0.800000  0.915523
11   q14  12  0.583333  0.583333  0.600706
12   q16   2  0.500000  0.500000  0.703918
13   q17   4  0.750000  0.750000  1.000000
14   q18   7  0.857143  0.857143  0.921738
15   q19   2  0.500000  0.500000  1.000000
16   q22   7  0.571429  0.571429  0.671756
17   q23   8  0.250000  0.250000  0.593878
18   q24   5  0.400000  0.400000  0.579969
19   q25   4  0.500000  0.500000  0.674482
20   q26   1  1.000000  1.000000  1.000000
21   q27   8  0.375000  0.375000  0.609813
22   q28   3  0.666667  0.666667  0.821275
23   q29  12  0.833333  0.833333  0.985397
24   q32   5  1.000000  1.000000  0.996048
25   q34   1  0.000000  0.000000  0.000000
26   q36  10  0.900000  0.900000  0.940251
27   q37   3  0.666667  0.666667  1.000000
28   q38   8  0.625000  0.625000  0.580879
29   q40   9  0.777778  0.777778  0.773743
30   q41   7  0.857143  0.857143  0.907619
31   q42   3  0.333333  0.333333  0.688529
32   q44  10  0.700000  0.700000  0.828469
33   q45   8  0.875000  0.875000  0.937373
34   q46   6  0.333333  0.333333  0.457959

In [51]:
tabla_evaluacion = resultados_bm25.copy()

tabla_evaluacion[["P@M", "R@M", "NDCG@M"]] = (
    tabla_evaluacion[["P@M", "R@M", "NDCG@M"]]
    .round(4)
)

display(tabla_evaluacion)

   query   M     P@M     R@M  NDCG@M
0    q01   3  0.6667  0.6667  0.5076
1    q02  11  0.5455  0.5455  0.5848
2    q03   6  1.0000  1.0000  0.9895
3    q04   7  0.8571  0.8571  0.8910
4    q06   6  0.6667  0.6667  0.8265
5    q07   4  0.2500  0.2500  0.5091
6    q08  12  0.7500  0.7500  0.8865
7    q09   6  1.0000  1.0000  0.9179
8    q10   8  0.3750  0.3750  0.4772
9    q12   4  0.7500  0.7500  0.7758
10   q13   5  0.8000  0.8000  0.9155
11   q14  12  0.5833  0.5833  0.6007
12   q16   2  0.5000  0.5000  0.7039
13   q17   4  0.7500  0.7500  1.0000
14   q18   7  0.8571  0.8571  0.9217
15   q19   2  0.5000  0.5000  1.0000
16   q22   7  0.5714  0.5714  0.6718
17   q23   8  0.2500  0.2500  0.5939
18   q24   5  0.4000  0.4000  0.5800
19   q25   4  0.5000  0.5000  0.6745
20   q26   1  1.0000  1.0000  1.0000
21   q27   8  0.3750  0.3750  0.6098
22   q28   3  0.6667  0.6667  0.8213
23   q29  12  0.8333  0.8333  0.9854
24   q32   5  1.0000  1.0000  0.9960
25   q34   1  0.0000  0.0000  0.0000
26   q36  10  0.9000  0.9000  0.9403
27   q37   3  0.6667  0.6667  1.0000
28   q38   8  0.6250  0.6250  0.5809
29   q40   9  0.7778  0.7778  0.7737
30   q41   7  0.8571  0.8571  0.9076
31   q42   3  0.3333  0.3333  0.6885
32   q44  10  0.7000  0.7000  0.8285
33   q45   8  0.8750  0.8750  0.9374
34   q46   6  0.3333  0.3333  0.4580

#### Coseno

In [52]:
resultados_coseno = evaluate_ranking(
    coseno_rankings,
    relevance_judgments
)

display(resultados_coseno)

   query   M       P@M       R@M    NDCG@M
0    q01   3  0.333333  0.333333  0.196954
1    q02  11  0.545455  0.545455  0.568734
2    q03   6  1.000000  1.000000  0.995943
3    q04   7  0.714286  0.714286  0.781593
4    q06   6  0.666667  0.666667  0.851844
5    q07   4  0.250000  0.250000  0.321204
6    q08  12  0.750000  0.750000  0.860365
7    q09   6  0.833333  0.833333  0.818389
8    q10   8  0.375000  0.375000  0.472121
9    q12   4  0.750000  0.750000  0.775845
10   q13   5  0.800000  0.800000  0.756922
11   q14  12  0.583333  0.583333  0.457038
12   q16   2  0.500000  0.500000  0.444123
13   q17   4  0.750000  0.750000  1.000000
14   q18   7  0.857143  0.857143  0.916478
15   q19   2  0.500000  0.500000  1.000000
16   q22   7  0.571429  0.571429  0.655936
17   q23   8  0.250000  0.250000  0.593878
18   q24   5  0.200000  0.200000  0.187334
19   q25   4  0.500000  0.500000  0.674482
20   q26   1  1.000000  1.000000  1.000000
21   q27   8  0.375000  0.375000  0.609813
22   q28   3  0.666667  0.666667  0.821275
23   q29  12  0.833333  0.833333  0.984226
24   q32   5  1.000000  1.000000  0.996048
25   q34   1  0.000000  0.000000  0.000000
26   q36  10  0.900000  0.900000  0.918152
27   q37   3  0.666667  0.666667  1.000000
28   q38   8  0.375000  0.375000  0.434374
29   q40   9  0.777778  0.777778  0.778027
30   q41   7  0.857143  0.857143  0.878988
31   q42   3  0.333333  0.333333  0.688529
32   q44  10  0.700000  0.700000  0.803927
33   q45   8  0.750000  0.750000  0.883670
34   q46   6  0.166667  0.166667  0.182033

In [53]:
resultados_coseno.columns

Index(['query', 'M', 'P@M', 'R@M', 'NDCG@M'], dtype='str')

In [54]:
tabla_evaluacion_coseno = resultados_coseno.copy()

tabla_evaluacion_coseno[["P@M", "R@M", "NDCG@M"]] = (
    tabla_evaluacion_coseno[["P@M", "R@M", "NDCG@M"]]
    .round(4)
)

display(tabla_evaluacion_coseno)

   query   M     P@M     R@M  NDCG@M
0    q01   3  0.3333  0.3333  0.1970
1    q02  11  0.5455  0.5455  0.5687
2    q03   6  1.0000  1.0000  0.9959
3    q04   7  0.7143  0.7143  0.7816
4    q06   6  0.6667  0.6667  0.8518
5    q07   4  0.2500  0.2500  0.3212
6    q08  12  0.7500  0.7500  0.8604
7    q09   6  0.8333  0.8333  0.8184
8    q10   8  0.3750  0.3750  0.4721
9    q12   4  0.7500  0.7500  0.7758
10   q13   5  0.8000  0.8000  0.7569
11   q14  12  0.5833  0.5833  0.4570
12   q16   2  0.5000  0.5000  0.4441
13   q17   4  0.7500  0.7500  1.0000
14   q18   7  0.8571  0.8571  0.9165
15   q19   2  0.5000  0.5000  1.0000
16   q22   7  0.5714  0.5714  0.6559
17   q23   8  0.2500  0.2500  0.5939
18   q24   5  0.2000  0.2000  0.1873
19   q25   4  0.5000  0.5000  0.6745
20   q26   1  1.0000  1.0000  1.0000
21   q27   8  0.3750  0.3750  0.6098
22   q28   3  0.6667  0.6667  0.8213
23   q29  12  0.8333  0.8333  0.9842
24   q32   5  1.0000  1.0000  0.9960
25   q34   1  0.0000  0.0000  0.0000
26   q36  10  0.9000  0.9000  0.9182
27   q37   3  0.6667  0.6667  1.0000
28   q38   8  0.3750  0.3750  0.4344
29   q40   9  0.7778  0.7778  0.7780
30   q41   7  0.8571  0.8571  0.8790
31   q42   3  0.3333  0.3333  0.6885
32   q44  10  0.7000  0.7000  0.8039
33   q45   8  0.7500  0.7500  0.8837
34   q46   6  0.1667  0.1667  0.1820

In [55]:
comparacion = pd.DataFrame({
    "query": resultados_coseno["query"],
    "M": resultados_coseno["M"],
    "P@M Coseno": resultados_coseno["P@M"],
    "P@M BM25": resultados_bm25["P@M"],
    "R@M Coseno": resultados_coseno["R@M"],
    "R@M BM25": resultados_bm25["R@M"],
    "NDCG@M Coseno": resultados_coseno["NDCG@M"],
    "NDCG@M BM25": resultados_bm25["NDCG@M"]
})

display(comparacion.round(4))

,query,M,P@M Coseno,P@M BM25,R@M Coseno,R@M BM25,NDCG@M Coseno,NDCG@M BM25
0,q01,3,0.3333,0.6667,0.3333,0.6667,0.1970,0.5076
1,q02,11,0.5455,0.5455,0.5455,0.5455,0.5687,0.5848
2,q03,6,1.0000,1.0000,1.0000,1.0000,0.9959,0.9895
3,q04,7,0.7143,0.8571,0.7143,0.8571,0.7816,0.8910
4,q06,6,0.6667,0.6667,0.6667,0.6667,0.8518,0.8265
5,q07,4,0.2500,0.2500,0.2500,0.2500,0.3212,0.5091
6,q08,12,0.7500,0.7500,0.7500,0.7500,0.8604,0.8865
7,q09,6,0.8333,1.0000,0.8333,1.0000,0.8184,0.9179
8,q10,8,0.3750,0.3750,0.3750,0.3750,0.4721,0.4772
9,q12,4,0.7500,0.7500,0.7500,0.7500,0.7758,0.7758
10,q13,5,0.8000,0.8000,0.8000,0.8000,0.7569,0.9155
11,q14,12,0.5833,0.5833,0.5833,0.5833,0.4570,0.6007
12,q16,2,0.5000,0.5000,0.5000,0.5000,0.4441,0.7039
13,q17,4,0.7500,0.7500,0.7500,0.7500,1.0000,1.0000
14,q18,7,0.8571,0.8571,0.8571,0.8571,0.9165,0.9217
15,q19,2,0.5000,0.5000,0.5000,0.5000,1.0000,1.0000
16,q22,7,0.5714,0.5714,0.5714,0.5714,0.6559,0.6718
17,q23,8,0.2500,0.2500,0.2500,0.2500,0.5939,0.5939
18,q24,5,0.2000,0.4000,0.2000,0.4000,0.1873,0.5800
19,q25,4,0.5000,0.5000,0.5000,0.5000,0.6745,0.6745
20,q26,1,1.0000,1.0000,1.0000,1.0000,1.0000,1.0000
21,q27,8,0.3750,0.3750,0.3750,0.3750,0.6098,0.6098
22,q28,3,0.6667,0.6667,0.6667,0.6667,0.8213,0.8213
23,q29,12,0.8333,0.8333,0.8333,0.8333,0.9842,0.9854
24,q32,5,1.0000,1.0000,1.0000,1.0000,0.9960,0.9960
25,q34,1,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
26,q36,10,0.9000,0.9000,0.9000,0.9000,0.9182,0.9403
27,q37,3,0.6667,0.6667,0.6667,0.6667,1.0000,1.0000
28,q38,8,0.3750,0.6250,0.3750,0.6250,0.4344,0.5809
29,q40,9,0.7778,0.7778,0.7778,0.7778,0.7780,0.7737
30,q41,7,0.8571,0.8571,0.8571,0.8571,0.8790,0.9076
31,q42,3,0.3333,0.3333,0.3333,0.3333,0.6885,0.6885
32,q44,10,0.7000,0.7000,0.7000,0.7000,0.8039,0.8285
33,q45,8,0.7500,0.8750,0.7500,0.8750,0.8837,0.9374
34,q46,6,0.1667,0.3333,0.1667,0.3333,0.1820,0.4580

In [56]:
evaluacion_rrdv = evaluate_ranking(coseno_rankings,relevance_judgments)
evaluacion_bm25 = evaluate_ranking(bm25_rankings,relevance_judgments)

In [57]:
map_cos = metricas.mean_average_precision(
    [[1 if document_id in relevance_judgments[query_id] else 0 for document_id, score in ranking]
        for query_id, ranking in coseno_rankings.items()
    ]
)

map_bm25 = metricas.mean_average_precision(
    [[1 if document_id in relevance_judgments[query_id] else 0 for document_id, score in ranking]
        for query_id, ranking in bm25_rankings.items()
    ]
)

print("MAP COS:", map_cos)
print("MAP BM25:", map_bm25)

MAP COS: 0.7047680299424705
MAP BM25: 0.7543733244416239

## Recuperación ranqueada con GENSIM

In [58]:
corpus = [document["tokens"] for document in documents]
dictionary = corpora.Dictionary(corpus)

corpus_bow = [dictionary.doc2bow(document["tokens"])for document in documents]

print("Tamaño del vocabulario - GENSIM:", len(dictionary))

tfidf = models.TfidfModel(corpus_bow,id2word=dictionary,smartirs="ltc")
corpus_tfidf = tfidf[corpus_bow]
index = similarities.SparseMatrixSimilarity(corpus_tfidf,num_features=len(dictionary),num_best=None)

gensim_rankings = {}

for query in queries:
    query_bow = dictionary.doc2bow(query["stems"])
    query_tfidf = tfidf[query_bow]
    scores = index[query_tfidf]
    ranking = [(documents[i]["id"], scores[i]) for i in np.argsort(scores)[::-1] if scores[i] > 0]
    gensim_rankings[query["id"]] = ranking

Tamaño del vocabulario - GENSIM: 13923

In [59]:
with open("GENSIM-consultas_resultados", "w", encoding="utf-8") as archivo:

    for query_id, ranking in gensim_rankings.items():

        resultados = [
            f"{document_id}: {score:.6f}"
            for document_id, score in ranking
        ]

        archivo.write(
            f"{query_id} {','.join(resultados)}\n"
        )

In [60]:
evaluacion_gensim = evaluate_ranking(gensim_rankings,relevance_judgments)

In [61]:
map_gensim = metricas.mean_average_precision(
    [[1 if document_id in relevance_judgments[query_id] else 0 for document_id, score in ranking]
        for query_id, ranking in gensim_rankings.items()
    ]
)
print("MAP GENSIM:", map_gensim)

MAP GENSIM: 0.7068766149575881

## Comparativa de metricas Finales

#### Tabla Comparativa metricas

In [62]:
evaluacion_comparativa = evaluacion_rrdv.merge(
    evaluacion_bm25,
    on=["query", "M"],
    suffixes=("_COS", "_BM25")
)

evaluacion_comparativa = evaluacion_comparativa.merge(
    evaluacion_gensim,
    on=["query", "M"]
)

evaluacion_comparativa = evaluacion_comparativa.rename(
    columns={
        "P@M": "P@M_GENSIM",
        "R@M": "R@M_GENSIM",
        "NDCG@M": "NDCG@M_GENSIM"
    }
)

evaluacion_comparativa["numero_query"] = (
    evaluacion_comparativa["query"].str[1:].astype(int)
)

evaluacion_comparativa = evaluacion_comparativa.sort_values(
    "numero_query"
).drop(columns="numero_query")

# evaluacion_comparativa = evaluacion_comparativa[
#     [
#         "query",
#         "M",
#         "P@M_COS",
#         "P@M_BM25",
#         "P@M_GENSIM",
#         "R@M_COS",
#         "R@M_BM25",
#         "R@M_GENSIM",
#         "NDCG@M_COS",
#         "NDCG@M_BM25",
#         "NDCG@M_GENSIM"
#     ]
# ]


evaluacion_comparativa = evaluacion_comparativa[
    [
        "query",
        "M",
        "P@M_GENSIM",
        "R@M_GENSIM",
        "NDCG@M_BM25",
        "NDCG@M_GENSIM"
    ]
]

display(evaluacion_comparativa.round(4))

   query   M  P@M_GENSIM  R@M_GENSIM  NDCG@M_BM25  NDCG@M_GENSIM
0    q01   3      0.3333      0.3333       0.5076         0.1970
1    q02  11      0.5455      0.5455       0.5848         0.5650
2    q03   6      1.0000      1.0000       0.9895         0.9959
3    q04   7      0.7143      0.7143       0.8910         0.7816
4    q06   6      0.8333      0.8333       0.8265         0.8497
5    q07   4      0.2500      0.2500       0.5091         0.3212
6    q08  12      0.7500      0.7500       0.8865         0.8582
7    q09   6      0.8333      0.8333       0.9179         0.8184
8    q10   8      0.3750      0.3750       0.4772         0.4683
9    q12   4      0.7500      0.7500       0.7758         0.7758
10   q13   5      0.8000      0.8000       0.9155         0.7665
11   q14  12      0.5833      0.5833       0.6007         0.4560
12   q16   2      0.5000      0.5000       0.7039         0.4441
13   q17   4      0.7500      0.7500       1.0000         1.0000
14   q18   7      0.8571      0.8571       0.9217         0.9137
15   q19   2      0.5000      0.5000       1.0000         1.0000
16   q22   7      0.4286      0.4286       0.6718         0.5754
17   q23   8      0.2500      0.2500       0.5939         0.5939
18   q24   5      0.2000      0.2000       0.5800         0.1873
19   q25   4      0.5000      0.5000       0.6745         0.6745
20   q26   1      1.0000      1.0000       1.0000         1.0000
21   q27   8      0.5000      0.5000       0.6098         0.7013
22   q28   3      0.6667      0.6667       0.8213         0.8213
23   q29  12      0.8333      0.8333       0.9854         0.9854
24   q32   5      1.0000      1.0000       0.9960         1.0000
25   q34   1      0.0000      0.0000       0.0000         0.0000
26   q36  10      0.9000      0.9000       0.9403         0.9182
27   q37   3      0.6667      0.6667       1.0000         1.0000
28   q38   8      0.3750      0.3750       0.5809         0.4239
29   q40   9      0.8889      0.8889       0.7737         0.7979
30   q41   7      0.8571      0.8571       0.9076         0.9610
31   q42   3      0.3333      0.3333       0.6885         0.6885
32   q44  10      0.7000      0.7000       0.8285         0.8039
33   q45   8      0.7500      0.7500       0.9374         0.8798
34   q46   6      0.1667      0.1667       0.4580         0.2297

#### Tabla Comparativa MPA

In [63]:
tabla_map = pd.DataFrame({
    "Función de ranqueo": [
        "COS",
        "BM25",
        "GENSIM"
    ],
    "MAP": [
        map_cos,
        map_bm25,
        map_gensim
    ]
})

display(tabla_map)

  Función de ranqueo       MAP
0                COS  0.704768
1               BM25  0.754373
2             GENSIM  0.706877